- .changeset/brown-zebras-tan.md
- packages/zod-validator/package.json
- packages/zod-validator/test/index.test.ts
- yarn.lock
Bum up Hono version to "3.0.0-rc.11" and fixed tests.
> chore(zod-validator): bump up Hono

- .changeset/loud-poems-retire.md
- packages/trpc-server/src/index.ts
This allows the use of options like `responseMeta` or `createContext`.
> tRPCOptions extends `FetchHandlerRequestOptions`-ish

- .changeset/sharp-rocks-prove.md
- packages/graphql-server/deno_dist/README.md
- packages/graphql-server/deno_dist/index.ts
- packages/graphql-server/deno_dist/parse-body.ts
- packages/graphql-server/deno_test/hono.test.ts
- packages/graphql-server/package.json
- packages/graphql-server/src/index.ts
This PR updates the GraphQL middleware to [Hono v3.0.0](https://github.com/honojs/hono/releases/tag/v3.0.0).
Overview of the changes:
- Update Hono dependencies from v2.7.5 to v.3.0.0
- ~`Requests` is now `HonoRequest` [src](https://github.com/honojs/hono/blob/main/docs/MIGRATION.md#creq-is-now-honorequest)~
- ~Update `graphql@16.6.0` import from `cdn.skypack.dev` to `esm.sh` due to Deno incompatibility~
EDIT:
- For this PR I think a version bump is needed
> feat: Update to Hono v3.0.0

- .changeset/thirty-snails-develop.md
- packages/firebase-auth/package.json
- packages/firebase-auth/src/index.ts
- yarn.lock
This PR enables Firebase Auth Middleware support Hono v3.
This may fix #59
> feat(firebase-auth): support Hono v3

- .changeset/kind-parents-play.md
- packages/sentry/deno_dist/index.ts
- packages/sentry/deno_test/deps.ts
- packages/sentry/package.json
- packages/sentry/src/index.ts
- yarn.lock
Sentry middleware currently expects that `SENTRY_DSN` or `NEXT_PUBLIC_SENTRY_DSN` are available in the request context. This causes the middleware to throw an undefined property error when given variables are not set.
This PR also bumps the Hono version due to changes in `MiddlewareHandler` type definition.
> Sentry middleware: fix undefined DSN environment variable error

- .changeset/clean-worms-thank.md
- packages/typebox-validator/src/index.ts
Cloudflare worker throws an EvalError when using TypeCompiler.Compile(schema).Check(data)
`Uncaught Error: EvalError: Code generation from strings disallowed for this context at index.js:5110:45 in Compile
`
https://github.com/sinclairzx81/typebox/issues/253
> Replaces TypeCompiler with Value

- .changeset/fair-trains-hope.md
- .github/workflows/ci-valibot-validator.yml
- package.json
- packages/valibot-validator/README.md
- packages/valibot-validator/jest.config.js
- packages/valibot-validator/package.json
- packages/valibot-validator/src/index.ts
- packages/valibot-validator/test/index.test.ts
- packages/valibot-validator/tsconfig.cjs.json
- packages/valibot-validator/tsconfig.esm.json
- packages/valibot-validator/tsconfig.json
- yarn.lock
Hello there,
this adds a [Valibot](https://valibot.dev/) middleware. It's a lightweight alternative to Zod with a very similar API and seems to be a good fit for Hono.
The implementation is basically just a copy of the Zod Middleware with minimal changes.
> feat(valibot-validator): Add Valibot Validator Middleware

- .changeset/thirty-geese-live.md
- packages/qwik-city/package.json
- packages/qwik-city/src/index.ts
- yarn.lock
Hi everyone,
The main focus of this PR is to adapt to the new `ServerRequestEvent` signature introduced in [qwik-city v1.2.0](https://github.com/BuilderIO/qwik/releases/tag/v1.2.0) by  https://github.com/BuilderIO/qwik/pull/4433
v1.1.5: https://github.com/BuilderIO/qwik/blob/v1.1.5/packages/qwik-city/middleware/request-handler/types.ts#L16-L24C2
v1.2.0: https://github.com/BuilderIO/qwik/blob/v1.2.0/packages/qwik-city/middleware/request-handler/types.ts#L31
To achieve this, the peerDependencies have been updated to target qwik-city v1.2.0 or higher. 
Additionally, the Hono version was previously pinned at 3.1.5, which was unnecessarily restrictive and forced middleware users to stick with that specific version. To provide more flexibility, the requirement has been changed to Hono v3.1.5 or …
> feat(qwik-city): adapt to v1.2.0 API and refine dependencies

- .changeset/fuzzy-spoons-crash.md
- packages/valibot-validator/package.json
- packages/valibot-validator/src/index.ts
- packages/valibot-validator/test/index.test.ts
- yarn.lock
closes #110 
Uses the exported `safeParse` result type.
> refactor(valibot-validator): update to latest valibot version

- .changeset/quiet-berries-accept.md
- .changeset/red-chefs-repeat.md
- .changeset/spotty-ads-act.md
- packages/zod-openapi/README.md
- packages/zod-openapi/src/index.ts
- packages/zod-openapi/test/index.test.ts
Three features are included in this PR:
1. You can pass init options to `OpenAPIHono` (fixes #152)
2. You can generate OpenAPI v3.1 spec
3. You can merge the spec definitions of nested `OpenAPIHono` routers
If you would prefer to handle these separately, they're in clean, distinct commits. 
New tests cover all new functionality. No old tests changed.
> [zod-openapi] Merge subapps' definitions into main app

- .changeset/lovely-laws-cry.md
- packages/zod-openapi/README.md
- packages/zod-openapi/src/index.ts
- packages/zod-openapi/test/createRoute.test.ts
closed: https://github.com/honojs/middleware/issues/159 
- Add getRoutingPath to the return value of createRoute
- Create getRoutingPath type from createRoute so that it can be referenced from `c.req.param`.
- Add tests for return value and type of getRoutingPath
> Add `getRoutingPath` to the return value of `createRoute`.

- .changeset/rare-pillows-change.md
- packages/zod-openapi/src/index.ts
Exported intermediate types representing the handler and the hook for a route so that handlers can be declared outside of the register method.
Like such
```ts
const route = createRoute({
method: 'get',
path: '/users/{id}',
request: {
params: ParamsSchema,
},
responses: {
200: {
content: {
'application/json': {
schema: UserSchema,
},
},
description: 'Retrieve the user',
},
},
})
const handler: RouteHandler<typeof route> = (c) => {
const { id } = c.req.valid('param')
return c.jsonT({
id,
age: 20,
name: 'Ultra-man',
})
}
app.openapi(route, handler)
```
> Zod-Openapi-Middleware: Export types to allow handlers and hooks to be declared in more places.

- .changeset/neat-mangos-compare.md
- packages/zod-validator/src/index.ts
Useful for weird stuff like this where it's needed to async parse a schema, since the parser does not parse requests such as the one below correctly it's an acceptable way to reach around it and make it work.
```
const formData = new FormData();
formData.append("input[0][id]", "1");
formData.append("input[1][id]", "2");
formData.append("input[2][id]", "3");
```
for context the above should parse as the following, but since we're using Response I understand why it doesn't
```json
{
"input": [
{ "id": "1" },
{ "id": "2" },
{ "id": "3" }
]
}
```
Example of code this PR enables below:
```ts
z.object({
zones: z.instanceof(File)
.refine(item => item.type === 'application/json')
.transform(async item => {
return JSON.parse(await item.text()) as LayerSchema;
})
.refine(items => {
return …
```
> add: Async zod support.

- .changeset/witty-dolls-raise.md
- packages/zod-openapi/README.md
- packages/zod-openapi/src/index.ts
- packages/zod-openapi/test/index.test.ts
Adds support for a `defaultHook` to avoid needing to pass the same error reformatter to every route.
If we're okay with this approach, I can add docs to the README.
Another option would be to export the types for `.openapi` and allow someone to create an `applyDefaultHook` similar to what I've shown here: https://tsplay.dev/NnMyaw
> feat(zod-openapi): add support for defaultHook in initializer

- .changeset/fresh-pillows-hear.md
- packages/zod-openapi/src/index.ts
- packages/zod-openapi/test/index.test.ts
> fix(zod-openapi): enable `basePath()`

- .changeset/slimy-singers-begin.md
- packages/zod-openapi/src/index.ts
This fixes the conversion from the openapi path type.
It's also recursive to convert all params instead of just one.
E.g.:
`/user/{id}/posts/{postId}/comments/{commentId}` to `/user/:id/posts/:postId/comments/:commentId`
> fix: properly convert openapi path type to hono

- .changeset/make-http-exception.md
- packages/firebase-auth/src/index.ts
I made to throw HTTPException instead of response null 401.
See: https://github.com/honojs/middleware/issues/185
Now, we can achieve our own error handling like the below:
```ts
app.onError((e, c) => {
if (e instanceof HTTPException && e.status === 401) {
return c.json(
{
message: 'Custom error message!',
},
401
)
}
return c.text('Internal Server Error', 500)
})
```
> fix(firebase-auth): throw HTTPException instead of reponse null

- packages/zod-openapi/package.json
- packages/zod-openapi/test/index.test.ts
- yarn.lock
I was trying to figure out how Authorisation headers will work with this repository. I discovered that there is some interesting behaviour with the capitalisation, and as such have added a test into the package to note this behaviour as seen here.
Additionally, I have removed a duplicate dependency from the `package.json` as this is already listed as a full dependency. In most scenarios, having a package listed twice the the `package.json` file is erroneous - I am sure if this was intentional someone will let me know 🙂
> test(zod-openapi): additional headers test for `Authorization`

- .changeset/old-readers-complain.md
- packages/graphql-server/src/index.ts
related #198 (I'm not familiar with Pothos, so I'm not sure...)
This commit introduces more specific type annotations to the following modules:
* `RootResolvers`
* `Options`
Specifically, the same type parameters used in the definition of `Context` class were given to them:
```ts
<E extends Env = any, P extends string = any, I extends Input = {}>
```
See: https://github.com/honojs/hono/blob/main/src/context.ts
To confirm, change `bun_test/index.test.ts` as follows (not included in the commit)
```ts
describe('graphql-server', () => {
// Construct a schema, using GraphQL schema language
const schema = buildSchema(`
type Query {
hello: String
}
`)
// My motivation is to development a GraphQL server on Cloudflare Workers with D1.
type Bindings = {
DB: string
}
type GraphQLContext = Context<{ …
```
> fix(graphql-server): enhance type safety of RootResolvers and Options

- .changeset/tough-beds-speak.md
- packages/zod-openapi/src/index.ts
- packages/zod-openapi/test/index.test.ts
With this PR, I made it allows the response type to be `Response` and not just `TypedResponse`.
Resolves #205
> feat(zod-openapi): allows the response to be `Response`

- .changeset/chilly-tomatoes-suffer.md
- packages/zod-validator/src/index.ts
- packages/zod-validator/test/index.test.ts
Fixes types for optional schema by making input optional (`?`) when the schema is optional.
See honojs/hono#1583
> fix(zod-validator): make validation input optional when schema is optional

- packages/zod-openapi/README.md
related: #261 
Since the guide was missing, we added a guide on authentication to the document to prevent the same question from occurring.
> docs(zod-openapi): add components registoration and auth configutation tips

- .changeset/tough-eels-exist.md
- packages/zod-openapi/README.md
- packages/zod-openapi/src/index.ts
- packages/zod-openapi/test/index.test.ts
> feat(zod-openapi): Make context accessible in the doc route

- .changeset/hip-owls-give.md
- packages/oauth-providers/src/providers/github/authFlow.ts
When using a GitHub App, instead of a GitHub OAuth App, no user can successfully authenticate because the state isn't added to the redirect URI.
> fix: ensure state is passed through for both github app types

- .changeset/two-crabs-speak.md
- packages/oauth-providers/src/providers/github/githubAuth.ts
OAuth apps can't have multiple callback URLs, but GitHub Apps can.
As such, we want to make sure we call back to the same location for GitHub apps and not the first configured callbackURL in the app config.
cc @yusukebe @monoald
> fix: redirect url for github apps

- packages/zod-openapi/README.md
`.hostname` doesn't include the protocol, which is important. =)
> Use origin for zod-openapi example

- .changeset/twelve-spiders-fail.md
- packages/react-renderer/README.md
- packages/react-renderer/package.json
- packages/react-renderer/src/global.d.ts
- packages/react-renderer/src/index.ts
- packages/react-renderer/src/react-renderer.ts
- packages/react-renderer/test/react-renderer.test.tsx
- packages/react-renderer/tsconfig.json
- packages/react-renderer/vitest.config.ts
- yarn.lock
This PR introduces the 'React Renderer Middleware'.
It is similar to the JSX Renderer Middleware in Hono's core, but it uses React. This might be used in Sonik or other meta-frameworks built on Hono. React supports not only server-side but also client-side rendering. Therefore, you can use it in a different way compared to Hono's JSX. Additionally, you can use a lot libraries available in React's ecosystem.
> feat: introduce React Renderer Middleware

- .changeset/nervous-berries-invent.md
- packages/zod-openapi/src/index.ts
This will let people create shareable defaultHooks, that way I can just use one snippet of code in all my sub routers.
> change: Export Hook in @hono/zod-openapi

- .changeset/great-queens-vanish.md
- packages/react-renderer/src/react-renderer.ts
To avoid throwing an error when `renderToReadableStream` is not available.
> fix(react-renderer): dynamic import `renderToReadableStream`

- .changeset/poor-cars-film.md
- packages/firebase-auth/package.json
- yarn.lock
In this PR, make Firebase Auth Middleware exports `esm` formatted package.
In Issue #335, `hono` was using `esm` and `@hono/firebase-auth` was using `cjs` so they did not reference the same `HTTPException` and the `res instanceof HTTPException` was not working properly. By using `@hono/firebase-auth` with this PR, both will use `esm` and the error will be gone.
Fixes #335
> fix(firebase-auth): export esm

- .changeset/little-plants-chew.md
- .changeset/loud-boats-fail.md
- packages/bun-transpiler/src/index.test.ts
- packages/bun-transpiler/src/index.ts
I noticed the previous implementation did not work when using serveStatic middleware. This fixes this.
> Fix: Apply headers when using serveStatic; Improvement: Make options optional;

- .changeset/friendly-carrots-help.md
- .github/workflows/ci-prometheus.yml
- package.json
- packages/prometheus/README.md
- packages/prometheus/package.json
- packages/prometheus/src/index.test.ts
- packages/prometheus/src/index.ts
- packages/prometheus/src/standardMetrics.ts
- packages/prometheus/tsconfig.json
- packages/prometheus/vitest.config.ts
- yarn.lock
Fixes https://github.com/honojs/hono/issues/263
As suggested in [this comment](https://github.com/honojs/hono/issues/263#issuecomment-1193129541), I'm adding this to the `honojs/middleware` repository instead of the main one as a third-party middleware.
I've tried to come up with sensible configuration options and default values based on my previous experiences with [express-prom-bundle](https://www.npmjs.com/package/express-prom-bundle) and [koa-prometheus](https://www.npmjs.com/package/@uswitch/koa-prometheus).
> Adding hono/prometheus middleware

- .changeset/curvy-lemons-give.md
- package.json
- packages/oidc-auth/package.json
Hi @yusukebe !
Thanks for releasing `@hono/oidc-auth`!
However, I noticed that there are no `dist/*` files in the npm package for `@hono/oidc-auth@1.0.0`.
This is due to the `yarn release` not executing the `build` script in the `package.json`.
I have fixed the `release` script to address this issue.
Additionally, `yarn publish` was a Yarn v1 command, so I have updated it to be compatible with v4.
Lastly, I noticed that the dependent library, `oauth4webapi`, does not support CommonJS.
As a result, I have updated the `package.json` to only build ESM.
> fix(oidc-auth): Fix "yarn release" for Yarn v4 / Build ESM only

- .changeset/old-suns-matter.md
- packages/valibot-validator/src/index.ts
- packages/valibot-validator/test/index.test.ts
Fixes types for optional schema by making input optional (`?`) when the schema is optional.
Exactly the same case as with `zod-validator` honojs/hono#1583
> fix(valibot-validator): make validation input optional when schema is optional

- .changeset/support-v4.md
- packages/firebase-auth/jest.config.js
- packages/firebase-auth/src/index.ts
fixed `TypeError: Cannot read properties of undefined (reading 'get')` error in hono v4
> fix(firebase-auth): retrive header values for v4

- .github/workflows/ci-arktype-validator.yml
- .github/workflows/ci-auth-js.yml
- .github/workflows/ci-clerk-auth.yml
- .github/workflows/ci-firebase-auth.yml
- .github/workflows/ci-graphql-server.yml
- .github/workflows/ci-hello.yml
- .github/workflows/ci-medley-router.yml
- .github/workflows/ci-prometheus.yml
- .github/workflows/ci-sentry.yml
- .github/workflows/ci-trpc-server.yml
- .github/workflows/ci-typebox-validator.yml
- .github/workflows/ci-typia-validator.yml
- .github/workflows/ci-valibot-validator.yml
- .github/workflows/ci-zod-openapi.yml
- .github/workflows/ci-zod-validator.yml
- .github/workflows/release.yml
As the title suggests, update actions/checkout and actions/setup-node to v4.
> ci: update actions/checkout and actions/setup-node to v4

- .changeset/add-verify-session-cookie-firebase-auth.md
- .gitignore
- packages/firebase-auth/README.md
- packages/firebase-auth/package.json
- packages/firebase-auth/src/index.ts
- packages/firebase-auth/test/index.test.ts
- packages/firebase-auth/tsconfig.json
- yarn.lock
Related: #377
- I have added new middleware that enables authentication and authorization using cookies.
- updated some deps.
- Hono remains on version 3, but it is compatible with version 4. This is to ensure that users who have not yet updated to v4 can still use this middleware.
> feat(firebase-auth): added a new middleware to verify session with firebase-auth

- .changeset/quiet-shrimps-rescue.md
- packages/zod-openapi/src/index.ts
- packages/zod-openapi/test/index.test.ts
There is currently an issue with basePath method where it does not transfer defaultHook to the newly created instance.
This pull request fixes it.
In the following code (taken from the current docs) the defaultHook is never called because it does not exist on the new instance created when basePath method is called.
```
const app = new OpenAPIHono({
defaultHook: (result, c) => {
if (!result.success) {
return c.json(
{
ok: false,
errors: formatZodErrors(result),
source: 'custom_error_handler',
},
422
)
}
},
}).basePath('/api/v1')
> fix(zod-openapi): Fix basePath method to transfer defaultHook of the parent app.

- .changeset/good-hairs-compare.md
- packages/react-renderer/src/react-renderer.ts
- Adds support for `renderToReadableStream` options in `(react-renderer)`
- Enables more flexible and performance-optimized hydration strategies
- Using react-renderer brings interaction to our hono application and also supports [\<Suspense\>](https://react.dev/reference/react/Suspense)
- Allows control of [render process options](https://react.dev/reference/react-dom/server/renderToReadableStream#parameters)
https://github.com/yoshikouki/hono-spa-react-bun/blob/46208aa2ffa6c9375ccea14e9d724496850e336c/src/index.tsx#L29-L37
```ts
// src/index.tsx
app.get(
"*",
reactRenderer(Layout, {
stream: true,
readableStreamOptions: {
bootstrapScripts: ["/src/client.tsx"],
},
})
);
app.get("/", (c) => {
return c.render(<App />);
});
```
```ts
// src/client.tsx
import { hydrateRoot } from …
```
> feat(react-renderer): Support renderToReadableStream options for hydration

- .changeset/twenty-windows-raise.md
- packages/react-renderer/src/react-renderer.ts
- packages/react-renderer/test/react-renderer.test.tsx
Correct the following issue
- https://github.com/honojs/middleware/issues/418
> fix(react-renderer): fix overwriting headers when stream is enabled

- .changeset/quiet-bulldogs-deny.md
- packages/zod-validator/jest.config.js
- packages/zod-validator/package.cjs.json
- packages/zod-validator/package.json
- packages/zod-validator/vitest.config.ts
- yarn.lock
Deno loading cjs file instead of esm module.
<details><summary>Сode with incorrect behavior</summary>
<p>
```typescript
#!/usr/bin/env -S deno run -Ar --watch
import {zValidator} from 'npm:@hono/zod-validator'
import {Hono} from 'npm:hono'
import {z} from 'npm:zod'
const app = new Hono()
const schema = z.object({val: z.string()})
app.post('/post', zValidator('form', schema), (c) => {
return c.json(c.req.valid('form'))
})
{
const res = await app.request('/post', {
method: 'POST',
headers: {'content-type': 'application/json'},
body: JSON.stringify({val: 'text'}), // incorrect data
})
console.log(res.status, res.status === 400) // expected 400
console.log(await res.text())
}
{
const res = await app.request('/post', {
method: 'POST',
headers: {'content-type': …
```
> fix(zod-validator): fix export for esm module

- .changeset/long-crabs-drum.md
- packages/zod-openapi/src/index.ts
- packages/zod-openapi/test/createRoute.test.ts
This prevents potential serialisation errors (e.g. yaml's `stringify`) of the return value of getOpenAPIDocument.
> zod-openapi: make getRoutingPath non-enumerable

- .changeset/eighty-doors-pull.md
- packages/clerk-auth/package.json
- packages/typebox-validator/package.json
- packages/valibot-validator/package.json
- yarn.lock
Widen the peer deps version range so that newer validation libraries can be installed. Fixes #442.
I followed the README instruction but am not familiar with changeset. Feel free to give some feedback if I made a mistake.
> chore(peer-deps): install newer peer depenencies

- .changeset/green-files-thank.md
- packages/oauth-providers/src/providers/google/googleAuth.ts
Minor adjustment to allow state to be a non required option while still falling back to the default random value if not provided
> Allow passing state in google oath middleware

- .changeset/itchy-dolls-crash.md
- packages/auth-js/src/index.ts
- packages/auth-js/test/index.test.ts
In the previous implementation, `AUTH_URL` was invalid because `c.req.raw` already includes the URL base. The provided URL base, `c.env.AUTH_URL`, will not be utilized. This issue will prevent the hono + auth.js project deployed behind a proxy from obtaining the correct `callback-url`.
> fix(auth-js): env AUTH_URL not working

- .changeset/tall-dingos-nail.md
- packages/trpc-server/src/index.ts
- packages/trpc-server/test/context.test.ts
https://github.com/honojs/middleware/pull/458 broke ability to create trpc contexts asynchronously (see attached screenshot). This PR fixes it by using async / await in the middleware.
> fix(trpc-server): Support asynchronous context creation

- .changeset/ninety-rules-give.md
- packages/swagger-ui/README.md
- packages/typebox-validator/test/index.test.ts
- packages/typia-validator/README.md
- packages/typia-validator/test/index.test.ts
Fixed a part of deprecated response json method in hono since v4.
`c.jsonT -> c.json`
source: [Migration Guide v3.12.x to v4.0.0](https://github.com/honojs/hono/blob/f2985492a30f14f9b2fbeffd5cc6b3aaeb34a2d1/docs/MIGRATION.md?plain=1#L11)
> fix: deprecated json response method

- .changeset/thin-dodos-marry.md
- packages/auth-js/src/index.ts
- packages/auth-js/src/react.tsx
@yusukebe  This pr deploy a fix for ssr  in react package  to work with remix and nextjs
> fix(auth-js): react package work with ssr

- .changeset/thin-fireants-work.md
- packages/valibot-validator/package.json
- packages/valibot-validator/src/index.ts
- packages/valibot-validator/test/index.test.ts
- yarn.lock
This PR will solves #501.
This includes changes below:
- Update `hono` version: Updated `hono` to the same version as zod-validator.
- Fix type inference: Corrected the type inference in `vValidator` based on the reference implementation in `zod-validator`.
- Add test for `number` query: Added a test case to validate type inference for `number` types in queries.
> [valibot-validator] Fix Type Inference for number Types in `valibot-validator` Query

- .changeset/lazy-files-appear.md
- packages/oauth-providers/src/providers/github/authFlow.ts
GitHub OAuth apps now only send the public email. The middleware has been updated to request the user's email using the received token for both OAuth apps and GitHub Apps
> Get email with github token

- .changeset/modern-buttons-impress.md
- packages/zod-openapi/src/index.ts
- packages/zod-openapi/test/handler.test-d.ts
- packages/zod-openapi/test/index.test.ts
> fix(zod-openapi): return type of handler should be MaybePromise

- .changeset/chatty-plants-dance.md
- packages/trpc-server/package.json
- packages/trpc-server/src/index.ts
- yarn.lock
in `trpc-server` middleware, we currently return the response directly which causes the respose to loose information about context. So if we set a header/cookie inside a trpc route, we don't get that in the respose.
I have fixed it by creating a new response object with `c.body` and returning that.
A reproduction of the issue can be found at https://github.com/BlankParticle/hono-header-reproduction/tree/main
> feat(trpc-server): use c.body to create response to avoid header loss

- .changeset/cuddly-pets-drum.md
- packages/zod-openapi/src/index.ts
- packages/zod-openapi/test/handler.test-d.ts
I addressed the missing support for the RouteHandler type in this PR #522 .
> fix(zod-openapi): update RouteHandler type to support MaybePromise

- .changeset/itchy-glasses-smell.md
- packages/zod-openapi/src/index.ts
#373
#432
I want to create a wrapper function for createRoute.
But, the current RouteConfig differs from the RouteConfig in @asteasolutions/zod-to-openapi.
It would be easy to define it myself, but it would be helpful if it is exported as there may be more differences in the future.
> feat(zod-openapi): export RouteConfig type

- .changeset/plenty-tables-beg.md
- .changeset/sharp-humans-flash.md
- packages/zod-openapi/src/index.ts
- packages/zod-openapi/test/index.test.ts
> feat(zod-openapi): extract range definitions to StatusCode

- packages/trpc-server/README.md
This PR adds documentation for configuring custom endpoints with the @hono/trpc-server middleware. Ensuring the endpoint parameter matches the middleware's path helps avoid issues like the one described in [honojs/middleware#166](https://github.com/honojs/middleware/issues/166).
> docs: add custom endpoint configuration example

- .changeset/itchy-eyes-warn.md
- packages/arktype-validator/package.json
- packages/arktype-validator/src/index.ts
- yarn.lock
This migrates `arktype-validator` to `arktype` 2.0, which is the current `latest` install.
> feat(arktype-validator): migrate to 2.0

- .changeset/yellow-lions-breathe.md
- packages/node-ws/src/index.test.ts
- packages/node-ws/src/index.ts
Currently, a new WebSocketServer is opened per websocket request. This PR reuses a single server for all requests.
> fix(node-ws): Create only one WebSocketServer instead of per websocket request

- .changeset/funny-dingos-obey.md
- packages/auth-js/src/client.ts
- packages/auth-js/src/index.ts
- packages/auth-js/src/react.tsx
- packages/auth-js/test/index.test.ts
@yusukebe  this pr fixes  https://github.com/honojs/middleware/issues/537
> handle x-forwarded headers to detect auth url

- .changeset/silly-chicken-suffer.md
- packages/zod-openapi/package.json
- packages/zod-openapi/src/index.ts
- packages/zod-openapi/test/index.test.ts
- packages/zod-openapi/yarn.lock
- yarn.lock
> fix(zod-openapi): support openapi yaml with middleware

- .changeset/five-horses-know.md
- packages/typia-validator/package.json
- yarn.lock
This commit updates the peer dependency of typia from ^5.0.4 to ^6.1.0 in the typia-validator package. The yarn.lock file has also been updated to reflect this change.
> feat(typia-validator): upgrade typia dependency to ^6.1.0

- .changeset/hungry-cameras-return.md
- packages/swagger-ui/src/swagger/renderer.ts
- packages/swagger-ui/test/option-renderer.test.ts
fixes #267
Adds support for the following Swagger-UI config options:
- `defaultModelsExpandDepth`
- `defaultModelExpandDepth`
- `defaultModelRendering`
- `displayRequestDuration`
- `filter`
- `showExtensions`
- `showCommonExtensions`
> fix(swagger-ui): Add support for several more configuration options

- .changeset/dull-frogs-glow.md
- packages/oauth-providers/src/providers/discord/discordAuth.ts
- packages/oauth-providers/src/providers/facebook/facebookAuth.ts
- packages/oauth-providers/src/providers/github/githubAuth.ts
- packages/oauth-providers/src/providers/google/googleAuth.ts
- packages/oauth-providers/src/providers/linkedin/linkedinAuth.ts
- packages/oauth-providers/src/providers/x/xAuth.ts
Hi, when using the middleware in node.js, I found it does not automatically read from process.env . Use of `hono/adapter` should fix this.
(correction welcome, I'm rather new to honojs)
> fix(oauth-providers): oauth-middleware: load `env.SECRETS` with hono/adapter

- .changeset/good-lizards-smile.md
- packages/auth-js/src/index.ts
- packages/auth-js/test/index.test.ts
@yusukebe This pr fixes issues on bun. As cloning  request like   `new Request(url,old)` doesn't work on bun yet which causes CRSF issues this pr uses getRuntimeKey from hono adapter to handle cloning for bun separetely.
> fix(auth-js): bun req cloning

- .changeset/happy-onions-carry.md
- packages/trpc-server/package.json
- packages/trpc-server/test/context.test.ts
- yarn.lock
Updates `@trpc/server` dependency to allow `11.0.0-rc.*` versions too.
~There has not been any changes to the fetch adapter, so no code change is required~
~There has been changes in the serialisation format of Trpc data, the tests were written with trpc 10.~
~The tests needs to be updated for Trpc 11, but that would break testing for trpc 10 (the package works fine with both 10/11, only the tests are the issue)~
According to Trpc's author batch is a boolean which is `1` for true and anything else is false, so the test is faulty. I have updated the tests.
>  chore: update `@hono/trpc-server` to allow using Trpc 11

- .changeset/olive-lies-cheat.md
- .github/workflows/ci-event-emitter.yml
- package.json
- packages/event-emitter/CHANGELOG.md
- packages/event-emitter/README.md
- packages/event-emitter/package.json
- packages/event-emitter/src/index.test.ts
- packages/event-emitter/src/index.ts
- packages/event-emitter/tsconfig.json
- packages/event-emitter/vitest.config.ts
- yarn.lock
I have created event-emitter middleware for Hono and as discussed [here](https://github.com/honojs/hono/pull/2843) I am opening a pull request in this repo instead of the main @hono/hono one as it is a better fit for it.
Thank you @yusukebe 
This middleware enables event-driven logic flow in hono applications (essential in larger projects or projects with a lot of interactions between features).
Inspired by event emitter concept in other frameworks such 
as [Adonis.js](https://docs.adonisjs.com/guides/emitter), [Nest.js](https://docs.nestjs.com/techniques/events), [Hapi.js](https://github.com/hapijs/podium), [Laravel](https://laravel.com/docs/11.x/events), [Sails.js](https://sailsjs.com/documentation/concepts/extending-sails/hooks/events), …
> Event Emitter middleware

- .changeset/tricky-bugs-switch.md
- packages/zod-openapi/src/index.ts
Fixes #631.
Just to add some context why I think it's valuable - I have plenty of zod schemas already and some of them aren't used by Hono at all, but I don't want to be limited and decide whether to use import from the middleware or directly from `zod`, I just want to use the `zod` export everywhere.
It's your call, but I'd even encourage using this method (i.e. using `extendZodWithOpenApi` instead of importing `z`) in the documentation as it gives much more flexibility.
> feat(zod-openapi): expose `extendZodWithOpenApi` from `zod-to-openapi`

- packages/graphql-server/README.md
- packages/graphql-server/src/index.ts
This Pull Request makes the following changes for consistency with other middleware:
- Changed the README example code to TypeScript.
- Renamed the variable representing `Context` from `ctx` to `c`.
> fix(graphql-server): update example code to Typescript and parameter name

- .changeset/serious-moose-push.md
- packages/zod-openapi/src/index.ts
- packages/zod-openapi/test/index.test.ts
While writing a JSON:API compliant REST API using zod-openapi, I ran into an issue where the `c.req.valid('json')` does not contain any data when sending request with Content-Type 'application/vnd.api+json', even though I did specify it in route definition.
So I fixed it.
It now also supports other similar content-types such as:
'application/json'
'application/vnd.api+json'
'application/problem+json'
'application/csp-report+json'
'application/vnd.custom+json'
...
> Support for other json content-types such as application/vnd.api+json, application/problem+json, etc.

- .changeset/light-goats-teach.md
- packages/node-ws/src/events.ts
- packages/node-ws/src/index.test.ts
- packages/node-ws/src/index.ts
Currently, `CloseEvent` doesn't exist in the latest versions of Node.js (v18.20.4, v20.15.1 and v22.4.) and you'll get the following error `Uncaught ReferenceError: CloseEvent is not defined` if you have this :
```javascript
app.get(
'/',
upgradeWebSocket(() => ({
onClose() {
// doing some stuff
},
}))
)
```
Fixes #595
> fix(node-ws): `CloseEvent` is not defined

- .changeset/cold-tigers-lie.md
- packages/oauth-providers/README.md
- packages/oauth-providers/src/providers/discord/discordAuth.ts
- packages/oauth-providers/src/providers/facebook/facebookAuth.ts
- packages/oauth-providers/src/providers/github/authFlow.ts
- packages/oauth-providers/src/providers/github/githubAuth.ts
- packages/oauth-providers/src/providers/google/googleAuth.ts
- packages/oauth-providers/src/providers/linkedin/authFlow.ts
- packages/oauth-providers/src/providers/linkedin/linkedinAuth.ts
- packages/oauth-providers/src/providers/x/xAuth.ts
- packages/oauth-providers/test/handlers.ts
- packages/oauth-providers/test/index.test.ts
Previously oauth middlewares only set redirect_uri from `c.req.url` which I felt restrictive:
1. hono (and the server process) may not be able to infer the redirect uri correctly. e.g. when it doesn't know its internet hostname.
2. developer may want to start oauth flow from routes other than the callback path.
3. developer may want to encode something into `redirect_uri`, like another redirect dest after authorization succeeds.
Allowing a custom `redirect_uri` would support these usages. Please see updated middleware readme for an example.
> feat(oauth-providers): allow custom redirect_uri

- .changeset/unlucky-cheetahs-fry.md
- packages/zod-openapi/src/index.ts
Fixes #646.
Just infer the `OpenAPIObjectConfig` instead of importing it from the internals, this way `"moduleResolution": "NodeNext"` users will have right intellisense.
I could, of course, just add the `.js` extension to the import, but i think the inferring is the way since it doesn't look like a hack.
> fix(zod-openapi): infer OpenAPIObjectConfig

- .changeset/soft-donuts-mix.md
- packages/graphql-server/src/index.ts
Added type to the GraphQL Server Middleware Handler and fixed it to accept a `Next` type argument.
> fix(graphql-server): add type to Middleware Handler

- .changeset/sixty-papayas-sin.md
- packages/graphql-server/README.md
- packages/graphql-server/src/index.ts
- packages/graphql-server/test/index.test.ts
> feat(graphql-server): add GraphiQL support

- .changeset/pretty-eels-prove.md
- .github/workflows/ci-conform-validator.yml
- package.json
- packages/conform-validator/README.md
- packages/conform-validator/package.json
- packages/conform-validator/src/index.ts
- packages/conform-validator/src/utils.ts
- packages/conform-validator/test/common.test.ts
- packages/conform-validator/test/hook.test.ts
- packages/conform-validator/test/valibot.test.ts
- packages/conform-validator/test/yup.test.ts
- packages/conform-validator/test/zod.test.ts
- packages/conform-validator/tsconfig.cjs.json
- packages/conform-validator/tsconfig.esm.json
- packages/conform-validator/tsconfig.json
- packages/conform-validator/vitest.config.ts
- yarn.lock
Added a validator that allows validation using [conform](https://conform.guide/). 
Although the processing content is highly abstract and does not do much, it can increase the affinity with  [Hono RPC](https://hono.dev/docs/guides/rpc).
> feat: Conform Validator Middleware

- .changeset/tender-knives-compare.md
- .github/workflows/ci-event-emitter.yml
- packages/event-emitter/README.md
- packages/event-emitter/package.json
- packages/event-emitter/src/index.test.ts
- packages/event-emitter/src/index.ts
- yarn.lock
This update contains the following
- New `emitAsync` method to the EventEmitter to enable invoking asynchronous handlers. 
- Added prevention for potential memory leak when adding handlers inside middleware via `on` method.
- Introduced new option of EventEmitter `maxHandlers` that limits number of handlers that can be added to a single event.
- Significantly improved documentation.
> feat(event-emitter): Enable invoking asynchronous handlers

- .changeset/rare-fishes-sort.md
- packages/oauth-providers/src/providers/google/authFlow.ts
- packages/oauth-providers/src/providers/google/googleAuth.ts
- packages/oauth-providers/test/index.test.ts
Added missing URL parameters `prompt`, `login_hint,` and `access_type` in the Google OAuth provider.
https://developers.google.com/identity/protocols/oauth2/web-server#httprest
> fix(@hono/oauth-providers): Added missing URL parameters prompt, login_hint, and access_type in the Google OAuth provider.

- .changeset/new-peaches-fix.md
- packages/graphql-server/src/index.ts
- packages/graphql-server/test/index.test.ts
This PR is to improve the type of root resolver function.
Closes  https://github.com/honojs/middleware/issues/655
> fix(graphql-server): the resolver always has context as the argument

- .changeset/beige-snails-cover.md
- packages/swagger-ui/src/swagger/resource.ts
- packages/swagger-ui/test/index.test.ts
- packages/swagger-ui/test/remote-assets.test.ts
https://6sense.com/tech/content-delivery-network-cdn/jsdelivr-vs-unpkg
In the Content Delivery Network (CDN) market, jsDelivr has a 21.23% market share in comparison to UNPKG's 1.24%.
Also, unpkg is blocked in China while jsdelivr is not
> perf(swagger-ui): use jsdelivr instead of unpkg to serve swagger-ui assets

- .changeset/clean-buses-shop.md
- packages/zod-openapi/src/index.ts
- packages/zod-openapi/test/index.test.ts
quick fix for #703. Does not differentiate between json-only response and mixed text/json response type, yet.
> feat(zod-openapi): allow multiple mimetype

- .changeset/gorgeous-berries-float.md
- packages/oidc-auth/README.md
- packages/oidc-auth/src/index.ts
- packages/oidc-auth/test/index.test.ts
- packages/oidc-auth/tsconfig.json
I'd like to use '`profile`' scope to get additional claims from google. In order to not having to forward all id claims to the session token, this pull request proposes an "`oidcClaimsHook`" as environment variable. If used, it has access to the claims, actual response (i.e. for retrieving full profile from access server) and returning claims for the session token.
Define environment variable to define oauth scope instead of full `scopes_supported`, e.g.
```
OIDC_SCOPES=openid email profile
```
Define an `oidcClaimsHook` to access original claims and return the ones for session token, e.g.:
```ts
import type { IDToken, OidcAuth, TokenEndpointResponses } from '@hono/oidc-auth';
declare module 'hono' {
interface OidcAuthClaims {
name: string
sub: string
}
}
const oidcClaimsHook = async …
```
> feat(oidc-auth): access and set claims

- packages/zod-openapi/README.md
This PR adds the required `info` arg to both `doc31` and `getOpenAPI31Document` functions. Without it, we get the below error:
> Argument of type '{ openapi: string; }' is not assignable to parameter of type 'OpenAPIObjectConfigure<Env, "/docs">'.
Property 'info' is missing in type '{ openapi: string; }' but required in type 'OpenAPIObjectConfig'.ts(2345)
openapi30.d.ts(7, 5): 'info' is declared here.
The type definition seems originated from [here](https://github.com/metadevpro/openapi3-ts/blob/71b55d772bacc58c127540b6a75d1b17a7ddadbb/src/model/openapi31.ts#L12-L14).
I also changed the comment `raw json` because getOpenAPI31Document returns an object, not a json string.
> docs(zod-openapi): fix missing arguments for `app.doc31`

- .changeset/olive-hounds-shout.md
- packages/zod-validator/src/index.ts
- packages/zod-validator/test/index.test.ts
Today, when we use `zod-openapi` and pass schema for `body` and `params`, we can pass a hook which is called with the result of the validation. 
The function doesn't get information about the target being validated. This is problematic when we want to return custom error responses depending on the target being validated. For example, one may want to:
-  return status `415 Unsupported Media Type` when body parsing failed due to missing content-type. Such behaviour doesn't make sense for `params`
- include in the error message the place where the validation failed. For `json` we may write in the response body 'body validation failed', for `params` 'path validation failed' and for `query` 'search params validation failed' .
This pull request adds this functionality.
> feat(zod-validator): pass target from zod-validator to a hook

- .changeset/hot-pumas-destroy.md
- packages/effect-validator/src/index.ts
- packages/effect-validator/test/index.test.ts
`@effect/schema` uses `TreeFormatter` as the default way of formatting errors. ([more here](https://github.com/Effect-TS/effect/tree/main/packages/schema#formatting-errors))
The result is hard to read in an http 400 response (although it is really nice in a terminal):
```json
{
"success": false,
"error": {
"_id": "ParseError",
"message": "{ readonly name: string; readonly password: string; readonly email: a string matching the pattern ^(?!\\.)(?!.*\\.\\.)([A-Z0-9_+-.]*)[A-Z0-9_+-]@([A-Z0-9][A-Z0-9-]*\\.)+[A-Z]{2,}$ }\n└─ [\"password\"]\n   └─ is missing"
}
}
```
With the `ArrayFormatter` it us much better:
```json
{
"success": false,
"error": [
{
"_tag": "Missing",
"path": [
"password"
],
"message": "is missing"
}
]
}
```
What are your thoughts about this ?
> feat(effect-validator): use array formatting for errors

- .changeset/purple-lizards-change.md
- packages/zod-openapi/src/index.ts
In #695, @bartekbp added a target property to the parameters of `zValidator` hooks. Since the version bump in #750, this property is already passed to validator hooks used with `zod-openapi`. This PR changes the `Hook` type of `zod-openapi` to include the `target` property.
> feat(zod-openapi): add target property to parameter of validation hook

- packages/auth-js/package.json
- packages/auth-js/src/index.ts
- packages/auth-js/test/index.test.ts
- yarn.lock
This pull request aims to remove the warning message: [auth][warn][env-url-basepath-redundant]. For more information, please see: https://warnings.authjs.dev#env-url-basepath-redundant.
> fix(auth-js): remove config.basePath

- .changeset/bright-teachers-remember.md
- packages/zod-validator/src/index.ts
- packages/zod-validator/test/index.test.ts
Closes https://github.com/honojs/hono/issues/2481
> feat(zod-validator): support enum types for `query`

- .changeset/sharp-ravens-shave.md
- packages/valibot-validator/package.json
- yarn.lock
I've updated the Valibot dependency of the adapter to v1. We've changed the type signature, so this change is necessary. All other changes in our v1 beta version are only internal.
---
An union of schema library authors (Zod, Valibot, ArkType, ...) collaborating on a standard interface for schema libraries called [Standard Schema](https://github.com/standard-schema/standard-schema). This simplifies implementation and prevents vendor lock-in. So far Valibot v1 supports this spec and Zod will follow soon. In the long run, the explicit implementation of a Valibot and Zod adapter may no longer be necessary.
> chore: update valibot dependency to v1

- packages/zod-openapi/README.md
The `> [!TIP]` block is now formatted correctly, allowing correct display within GitHub.
> docs(zod-openapi): fix tip block in readme

- .changeset/rotten-tips-camp.md
- packages/auth-js/README.md
- packages/auth-js/src/client.ts
- packages/auth-js/src/index.ts
- packages/auth-js/src/react.tsx
- packages/auth-js/test/index.test.ts
@yusukebe This pr improves Session Provider implementation which was initially taken from next-auth. Composing useEffect logic into separate hooks  to make code more readable and  change in login  function to support Popup Window login which will be added in example repo later.
> refactor(auth-js): session provider

- .changeset/slimy-geese-promise.md
- packages/auth-js/README.md
- packages/auth-js/src/client.ts
- packages/auth-js/src/index.ts
- packages/auth-js/src/react.tsx
- packages/auth-js/test/index.test.ts
As bun now supports request cloning from  version 1.26 onwards  so workaround for cloning can be removed now @yusukebe. Ran test suite using bun its working fine. Also added popup login hook from example repo so that it can be imported directly from here.
> fix(auth.js): clone request directly for bun

- .changeset/bright-teachers-knock.md
- packages/oidc-auth/README.md
- packages/oidc-auth/src/index.ts
- packages/oidc-auth/test/index.test.ts
I want to add a environment variable `OIDC_COOKIE_NAME` that allows the cookie name used to be customized, which will enhance security, avoid namespace conflicts, etc.
- Added a configuration option `OIDC_COOKIE_NAME`
- Merged validation logic for all environment variables in `getOidcAuthEnv()`
- Tested custom cookie names. (default name test is done in other tests).
- Verified no impact on authentication flow.
> feat(oidc-auth): optional cookie name

- .changeset/early-tools-press.md
- packages/valibot-validator/package.json
- yarn.lock
Looks like the npm install broke with the upgrade to Valibot v1. This PR should fix that.
> fix(valibot-validator): add support for v1 dist-tags

- .changeset/shy-pigs-buy.md
- packages/zod-openapi/src/index.ts
- packages/zod-openapi/test/index.test-d.ts
This PR is my initial proposal for adding type inference support for the zod-openapi middleware package, improving type safety when using middleware within the router definition.
**Example usecase:**
https://github.com/honojs/middleware/blob/aca9bfd35f775fd455a0ceb9ed37e617d698571d/packages/zod-openapi/test/index.test-d.ts#L268-L304
**Background**
I'm fairly new to HonoJS, but I've been very excited to explore its potential, especially the zod-openapi integration. However, I noticed that middleware types seem to be dropped when used alongside the OpenAPI package, which can impact type consistency and developer experience.
**Potentially resolving:**
* https://github.com/honojs/middleware/issues/715
* https://github.com/honojs/middleware/issues/637
* ...
**Potential alternative**
* …
> feat(zod-openapi): infer env from routeMiddleware

- packages/zod-openapi/README.md
With this PR I am changing the middleware example of zod-openapi to use a tuple.
**Potentially resolving:**
https://github.com/honojs/middleware/issues/637
> docs(zod-openapi): use tuple in middleware example

- .changeset/two-poets-vanish.md
- .github/workflows/ci-ajv-validator.yml
- package.json
- packages/ajv-validator/README.md
- packages/ajv-validator/package.json
- packages/ajv-validator/src/index.ts
- packages/ajv-validator/test/index.test.ts
- packages/ajv-validator/tsconfig.json
- packages/ajv-validator/vitest.config.ts
- yarn.lock
Hello,
I'd like to contribute an [Ajv](https://github.com/ajv-validator/ajv) validator middleware for Hono.
The implementation is primarily based on the existing Zod validator middleware, with minimal changes to accommodate Ajv's API. I've also included test cases similar to those used for the TypeBox and Zod validators.
> feat(ajv-validator): Add Ajv validator middleware

- .changeset/red-toes-reflect.md
- packages/zod-openapi/src/index.ts
- packages/zod-openapi/test/handler.test-d.ts
#807 introduced inference of `env` based on middleware. However, this was not extended to some of the abstract types themselves - this PR fixes this.
> fix(zod-openapi): infer env type parameter from middleware

- .changeset/eleven-islands-jump.md
- .github/workflows/ci-tsyringe.yml
- packages/tsyringe/README.md
- packages/tsyringe/package.json
- packages/tsyringe/src/index.test.ts
- packages/tsyringe/src/index.ts
- packages/tsyringe/tsconfig.json
- packages/tsyringe/vitest.config.ts
- yarn.lock
This middleware uses `tsyringe` to provide dependency injection support for Hono and can construct objects with `c.var.resolve(MyService)`
```ts
@injectable()
class Client {
private readonly apiKey: string;
constructor(@inject(Config) config: Config) {
this.apiKey = config.apiKey
}
// ...
}
app.use('*', tsyringe(
(c, container) => {
container.register(Config, { useValue: new Config(c.env.API_TOKEN)) }
}
))
app.get('/foo', async (c) => {
const apiClient = c.var.resolve(Client)
const reply = await apiClient.hello()
return c.text(reply)
})
```
> feat(tsyringe): add @hono/tsyringe middleware

- .changeset/swift-pigs-smile.md
- packages/swagger-ui/src/index.ts
This pull request includes updates to the `SwaggerUI` middleware to allow customization of the HTML title. The most important changes include adding a `title` option to the `SwaggerUIOptions` type and updating the middleware to use this new option.
Enhancements to `SwaggerUI` middleware:
* [`packages/swagger-ui/src/index.ts`](diffhunk://#diff-8acefcfd603b5fa0a8a33b63d561ff1fa4ea5e40230e7aece4e18068b2a916a1R38): Added a `title` property to the `OriginalSwaggerUIOptions` type.
* [`packages/swagger-ui/src/index.ts`](diffhunk://#diff-8acefcfd603b5fa0a8a33b63d561ff1fa4ea5e40230e7aece4e18068b2a916a1R72-R79): Updated the `SwaggerUI` middleware to use the `title` option, defaulting to "SwaggerUI" if not provided.
> feat: customize html title for swagger-ui

- .changeset/stale-hairs-wonder.md
- packages/zod-openapi/src/index.ts
- packages/zod-openapi/test/handler.test-d.ts
Fixed the inference of complex types in `zod-openapi`.
Issue explained in detail [here](https://github.com/honojs/middleware/issues/847)
> fix(zod-openapi): multi-middleware complex type inference

- .changeset/fluffy-doors-carry.md
- packages/zod-openapi/src/index.ts
- packages/zod-openapi/test/handler.test-d.ts
- packages/zod-openapi/test/index.test-d.ts
- packages/zod-openapi/test/index.test.ts
Fixes #842
#852 was a great PR to fix #842. However, type errors should not arise for responses other than HTML. Example: 
`application/xml`. So, the problem will be solved if we set `Response` to contents other than JSON or Text like the following.
* JSON - `TypedRespose` with `json`
* Text - `TypedResponse` with `text`
* Others - `Response`
This PR will correct whether the returned value should be a `TypedResponse` or a `Response` based on the specified content type.
> fix(zod-openapi): return `Response` if response is not text or JSON

- .changeset/red-files-fly.md
- packages/effect-validator/package.json
- packages/effect-validator/src/index.ts
- packages/effect-validator/test/index.test.ts
- yarn.lock
The `@effect/schema` package has been migrated from [Effect-TS/schema](https://github.com/Effect-TS/schema) to [Effect-TS/effect](https://github.com/Effect-TS/effect).
As a result, all `@effect/schema` imports have been updated to `effect`.
During the update, I encountered type errors, which have been resolved.
Since `import { Schema } from 'effect'` was introduced in version 3.10.0, I added `effect@3.10.0` to `peerDependencies`.
> feat: support `effect@3.10.0`

- .changeset/spotty-hounds-relate.md
- packages/trpc-server/src/index.ts
wrap Request with Proxy getter receiver should Request-instance
> fix(trpc-server) The Request.url getter can only be used on instances of Request

- .changeset/sharp-moles-knock.md
- .github/workflows/ci-cloudflare-access.yml
- package.json
- packages/cloudflare-access/README.md
- packages/cloudflare-access/package.json
- packages/cloudflare-access/src/index.test.ts
- packages/cloudflare-access/src/index.ts
- packages/cloudflare-access/tsconfig.json
- packages/cloudflare-access/vitest.config.ts
- yarn.lock
usage:
```
app.use('*', cloudflareAccess('my-access-team-name'))
```
access jwt payload
```
app.get('/', (c) => {
const payload = c.get('accessPayload')
return c.text(`You just authenticated with the email ${payload.email}`)
})
```
> feat: Add Cloudflare Access middleware

- .changeset/support-http-module.md
- packages/typia-validator/.gitignore
- packages/typia-validator/README.md
- packages/typia-validator/package.json
- packages/typia-validator/scripts/add-ts-ignore.cjs
- packages/typia-validator/src/http.ts
- packages/typia-validator/src/index.ts
- packages/typia-validator/test/http.test.ts
- packages/typia-validator/test/index.test.ts
- yarn.lock
- **Added HTTP Module Support:** Enables handling of `number`, `boolean`, and `bigint` types in query parameters and headers by integrating the [HTTP module](https://typia.io/docs/misc/#http-module). This enhancement allows for more robust and type-safe data validation within requests.
- **Updated `typia` Peer Dependencies:** Increased the required `typia` version to `7.0.0` or higher. This update is necessary to utilize the `IReadableURLSearchParams` interface, which is available starting from version 7, ensuring compatibility and leveraging the latest features of `typia`.
> feat(typia-validator): support typia http module

- .changeset/heavy-bugs-perform.md
- packages/cloudflare-access/README.md
- packages/cloudflare-access/src/index.test.ts
- packages/cloudflare-access/src/index.ts
In the current version of `@hono/cloudflare-access`, both of the actions bellow will result into an "internal error" with a stack trace from the middleware:
- defining an access team name that does not exist
- fetching the access certificates when access is "generally" unavailable
This pr adds a good error message that correctly describes what the middleware received from Cloudflare Access.
This throws normal JS Error's because this is a fatal exception that the user should handle, but if the Hono maintainers think otherwise, i'm happy to change this into `throw new HTTPException(500, { message: '...' })`
> feat(cloudflare-access): Handle Access organization does not exist and Access not available cases

- packages/zod-validator/README.md
…dating error instead of directly returning an error response. 
throw a validating error instead of directly returning an error response.
relate pr: #897
close: #890
> docs(zod-validator): add usage docs for `zErrValidator`

- packages/zod-validator/README.md
This PR updates the `README.md` file to include a custom `zValidator` wrapper example that improves type inference for validated data.  
- Added a new section titled "Custom Wrapper for Improved Type Inference".  
- Included an example of a generic wrapper that leverages TypeScript generics to ensure correct type inference.
Closes #921.
> @hono/zod-validator - Update README.md to include an example with a custom validator wrapper for improved type inference

- .changeset/ten-trainers-jam.md
- packages/oidc-auth/README.md
- packages/oidc-auth/src/index.ts
- packages/oidc-auth/test/index.test.ts
closes: https://github.com/honojs/middleware/issues/760
I want to add a environment variable `OIDC_COOKIE_DOMAIN` that allows to set `domain` cookie attribute, which will enhance usage of authentication
- Added a configuration option `OIDC_COOKIE_DOMAIN`
- Tested case of environment value set and not set
- Verified no impact on authentication flow.
> feat(oidc-auth): optional cookie domain

- .changeset/warm-plants-thank.md
- packages/valibot-validator/src/index.ts
- packages/valibot-validator/test/index.test.ts
This middleware addresses https://github.com/honojs/middleware/issues/899.
> fix(valibot-validator): Fix response query types on RPC

- .changeset/kind-cheetahs-give.md
- packages/oidc-auth/README.md
- packages/oidc-auth/src/index.ts
- packages/oidc-auth/test/index.test.ts
The `OIDC_REDIRECT_URI` was initially expected to be a full URL, but rewriting the URL for development and production environments is cumbersome. By supporting absolute paths such as `/callback`, we aim to reduce the developer’s effort.
- Added support for absolute paths in `OIDC_REDIRECT_URI` and set the default value to `/callback`.
- Verified the behavior when `OIDC_REDIRECT_URI` is a relative path and when it is not set.
- Added tests for other environment variables.
> feat(oidc-auth): support absolute path for redirect URI

- .changeset/eighty-trains-peel.md
- packages/oidc-auth/src/index.ts
While running the oidc-oauth test, I encountered the following error. Therefore, I have fixed it.
The test worked in other environments, so I suspect that the issue was caused by the esbuild version update.
```
src/index.ts:152:7 - error TS2322: Type 'JWTPayload' is not assignable to type 'Partial<OidcAuth>'.
'string' index signatures are incompatible.
Type 'unknown' is not assignable to type 'JsonValue | undefined'.
152       auth = await verify(session_jwt, env.OIDC_AUTH_SECRET)
~~~~
src/index.ts:248:69 - error TS2345: Argument of type '{} | null' is not assignable to parameter of type 'string'.
Type 'null' is not assignable to type 'string'.
248         const response = await oauth2.revocationRequest(as, client, auth.rtk)
~~~~~~~~
```
- Fixed type error
> fix(oidc-auth): Fixed type error

- .changeset/metal-kiwis-doubt.md
- packages/node-ws/package.json
- packages/node-ws/src/index.ts
- yarn.lock
> fix(node-ws): Added missing WSContext raw type

- .changeset/purple-weeks-cross.md
- packages/typebox-validator/package.json
Adds package.json to the esm build folder with `"type": "module"`, so that the runtime recognises the type of the package as esm. Then it will import typebox as esm. Fixes #873
> fix(typebox-validator): Fix @hono/typebox-validator, when imported as esm, transiently importing typebox as cjs

- .changeset/breezy-moose-hide.md
- packages/typebox-validator/package.json
> fix(typebox-validator): correct exporting in `package.json`

- .changeset/ninety-dogs-decide.md
- packages/node-ws/package.json
- packages/node-ws/src/index.test.ts
- packages/node-ws/src/index.ts
Fixes #948
`Hono<any, any, any>` can accept an app with custom Bindings/Variables types. This method is used in such the code:
https://github.com/honojs/hono/blob/093d3fd56ea4411aab305984dbc29e24ac3ac528/src/client/client.ts#L122
> fix(node-ws): allow `Hono` with custom Env for `createNodeWebSocket`

- .changeset/heavy-trains-serve.md
- packages/zod-openapi/src/index.ts
- packages/zod-openapi/test/index.test.ts
> fix(zod-openapi): handle nested app base paths in openapi registration

- .changeset/gorgeous-crabs-doubt.md
- packages/standard-validator/src/index.ts
- packages/standard-validator/test/__schemas__/arktype.ts
- packages/standard-validator/test/index.test.ts
fix type error
```typescript
import { Hono } from "hono";
import { minLength, object, pipe,  string } from "valibot";
const createSchema = object({
name: pipe(string(), minLength(3)),
});
const route = new Hono()
.post(
"/",
sValidator("form", createSchema, (result, c) => {
if (!result.success) {
return c.json({ errors: result.error }, 400);  // <- type error
}
}),
async (c) => {
const { name } = c.req.valid("form");
return c.json({name});
}
);
```
```
Property 'error' does not exist on type '({ success: boolean; data: { name: string; }; } | { success: boolean; error: readonly Issue[]; data: { name: string; }; }) & { target: "form"; }'.
Property 'error' does not exist on type '{ success: boolean; data: { name: string; }; } & { target: "form"; }'
```
> fix(standard-validator): fix hook's  result type

- .changeset/curly-fans-rhyme.md
- packages/react-renderer/src/react-renderer.ts
- packages/react-renderer/test/react-renderer.test.tsx
> feat(react-renderer): Include a doctype statement by default

- .changeset/selfish-lies-sing.md
- packages/node-ws/src/index.test.ts
- packages/node-ws/src/index.ts
This PR addresses an issue in which WebSocket connections are permanently established even when the app does not expect them. As a result, these unwanted connections remain active indefinitely, potentially leading to resource leaks and other unintended behavior.
- The server currently accepts all WebSocket connection attempts without verifying if the app expects them.
- Unwanted WebSocket connections remain open, causing unnecessary resource consumption and potential security risks.
If the server detects a WebSocket connection that is not expected by the application, it immediately rejects the handshake and closes the connection.
This behaviour can be disabled by  ```createNodeWebSocket({ app, strict: false })```
> feat(node-ws): Reject unexpected WebSocket connections

- .changeset/hot-moles-fix.md
- packages/zod-openapi/README.md
- packages/zod-openapi/src/index.ts
- packages/zod-openapi/test/index.test.ts
Similar to what is available here: https://github.com/rhinobase/hono-openapi?tab=readme-ov-file#conditionaly-hiding-routes
> Add ability to exclude routes from OpenAPI docs

- .changeset/sixty-tomatoes-fold.md
- packages/swagger-ui/src/swagger/renderer.ts
- packages/swagger-ui/test/option-renderer.test.ts
This PR fixes #974 
* [`packages/swagger-ui/src/swagger/renderer.ts`](diffhunk://#diff-ccca2844de07070d9888be6dfd16d8521ec7274b90337478481a5343b0b88191L130-R151): Enhanced the `renderSwaggerUIOptions` function to handle undefined options and improve rendering logic for non-RENDER_TYPE_MAP edge cases. Added a switch statement to manage different render types and a filter to remove empty strings from the options.
* [`packages/swagger-ui/test/option-renderer.test.ts`](diffhunk://#diff-6ce2374220877a06c4f196ed2d4c04657516f0c789f5f862739864ca37f26c0bR190-R214): Added tests to ensure the `renderSwaggerUIOptions` function correctly filters out properties not in `RENDER_TYPE_MAP`, handles undefined values, manages multiple invalid properties gracefully, and handles empty input gracefully.
> fix(swagger-ui): fix configuration bug

- .changeset/dry-squids-flash.md
- packages/zod-openapi/src/index.ts
- packages/zod-openapi/test/index.test.ts
> fix(zod-openapi): replace path param strings correctly in basePath

- .changeset/smooth-grapes-pay.md
- packages/zod-openapi/src/index.ts
- packages/zod-openapi/test/index.test.ts
This fixes an issue, that wasn't covered by #992.
I don't know where to actually put the `replaceAll`, because if it put it before the `app.openAPIRegistry`, `_basePath` isn't always defined and therefore will fail.
> fix(zod-openapi): correctly handle path parameters in basePath

- .github/workflows/ci-auth-js.yml
- packages/auth-js/test/index.test.ts
Avoid needing to override `global.crypto` in tests
> test(auth-js): use node 20.x in CI

- .changeset/famous-starfishes-change.md
- .github/workflows/ci-otel.yml
- package.json
- packages/otel/README.md
- packages/otel/package.json
- packages/otel/src/index.test.ts
- packages/otel/src/index.ts
- packages/otel/tsconfig.json
- packages/otel/vitest.config.ts
- yarn.lock
This middleware addresses <https://github.com/honojs/hono/issues/1864>.  For usage, see also the README file.
> feat(otel): Add OpenTelemetry middleware

- .github/workflows/ci-coverage.yml
Whoops.. Looks like I missed actually uploading coverage on `main` 🙈 sorry!
Once this is done, we should be able to remove `.github/workflows/ci-coverage.yml`
> ci: initial coverage

- .changeset/perfect-shoes-laugh.md
- packages/typia-validator/package.json
- yarn.lock
After upgrading typia to version 8.0.0, the project’s peer dependencies are breaking. Despite the major version bump, all tests are passing.
> chore(typia): bump 8.0.3

- .changeset/tall-llamas-refuse.md
> fix(typebox-validator): export modules correctly

- packages/zod-openapi/README.md
This adds a note on the usage of `.route` with params with zod-openapi middleware.
Closes #977
> docs:(zod-openapi): add note about app.route

- .changeset/violet-melons-glow.md
- packages/oauth-providers/src/providers/x/authFlow.ts
The twitter authorization URL didn't work for me. Patched it locally to `x.com/[...]` and it works for me.
> fix(oauth-providers): Update twitter authorization url

- .changeset/dark-kiwis-check.md
- packages/zod-openapi/src/index.test-d.ts
- packages/zod-openapi/src/index.ts
- packages/zod-openapi/tsconfig.spec.json
Fixes the issue commented on https://github.com/honojs/middleware/issues/1102#issuecomment-2781766226
> fix(zod-openapi): infer Env correctly if the middleware is `[]`

- .changeset/full-words-design.md
- .github/workflows/release.yml
- package.json
Due to changesets/changesets#674 the `workspace:` protocol isn't handled correctly.
Using [`yarn npm publish`](https://yarnpkg.com/cli/npm/publish) will update the workspace reference during publishing.
This van be verified by running pack in every workspace..
`yarn workspaces foreach --all --topological pack`
..or just from `@hono/zod-openapi`
`yarn workspaces foreach --from @hono/zod-openapi --recursive --topological --verbose pack`
Both commands will pack `@hono/zod-validator` before `@hono/zod-openapi`, and the workspace reference in the `package.tgz` will point to the current version of `@hono/zod-validator`
fixes #1109
> fix(zod-openapi): republish without workspace reference

- .github/workflows/release.yml
Restore `yarn build` during the release
This should ensure everything is built before anything is published
> ci(release): restore build during release

- packages/conform-validator/README.md
- packages/conform-validator/package.json
- packages/conform-validator/src/valibot.test.ts
- yarn.lock
The form library [Conform](https://github.com/edmundhung/conform) now officially supports valibots, so the description has been revised.
Until now, Conform required the use of a library called conform-to-valibot to use valibot, but this [Pull Request](https://github.com/edmundhung/conform/pull/876) has made it officially supported.
So I changed the library listed in the test code and README. Changing the library does not change the API.
> chore(conform-validator): Change conform valibot adapter to official library

- .changeset/proud-shrimps-try.md
- packages/zod-openapi/package.json
- yarn.lock
Ran into some issues related to https://github.com/asteasolutions/zod-to-openapi/pull/281 in our codebase, where we implemented format string schemas using `z.custom`. In Zod 4 we will migrate to the new format literals, but in the meanwhile opening this PR to bump the dependency minor version to include this bug fix.
Please let me know if I should add a test!
> chore(zod-openapi): lock zod-to-openapi to `^7.3.0` to fix `z.custom`

- .changeset/salty-bags-shop.md
- packages/otel/src/index.ts
One of Open Telemetry's main feature is the ability to trace across micro services, this updates the `@hono/otel` package to check if `traceparent` is set and if so then set the context for the span to match accordingly.
> feat(otel): Added support for W3C Trace Context format

- .changeset/two-ends-fetch.md
- packages/graphql-server/src/index.ts
I propose to update GraphiQL with what is suggested in the official repository example :
https://github.com/graphql/graphiql/blob/main/examples/graphiql-cdn/index.html
I'm not sure if it's a minor or major change.
> feat(graphql-server): upgrade GraphiQL

- .changeset/hot-singers-smell.md
- packages/eslint-config/index.js
Adds a `@type` declaration for the default export of `@hono/eslint-config `
fixes #1157
> feature(eslint-config): add types

- package.json
Calling `changeset tag` after publishing packages _should_ trigger `changesets/actions` to add releases to GitHub
> It looks like `changesets/actions` uses the output of the publish command (`changesetPublishOutput`)
> 
> https://github.com/changesets/action/blob/ff7179cf129faeb3e444f56e6290adef5901f936/src/run.ts#L127-L131
> 
> to look for packages that were published, and pushes any matches to `releasedPackages`
> 
> https://github.com/changesets/action/blob/ff7179cf129faeb3e444f56e6290adef5901f936/src/run.ts#L142-L156
> 
> The output from `yarn npm publish` is a different format, so no release get added to GitHub 
_Originally posted by @BarryThePenguin in [#1124](https://github.com/honojs/middleware/issues/1124#issuecomment-2796549220)_
The output of `changeset tag` is in the correct …
> fix(release): publish tags

- .gitignore
- eslint.config.mjs
- packages/event-emitter/src/index.ts
- packages/graphql-server/src/index.ts
- packages/standard-validator/src/index.test.ts
- packages/standard-validator/src/index.ts
- packages/typebox-validator/src/index.test.ts
While I had some time I thought I'd review some lint rules from #1098
This enables PR [`@typescript-eslint/array-type`](https://typescript-eslint.io/rules/array-type/), a stylistic rule that prefers
- `T[] or readonly T[]` ✅ 
- `Array<T>, ReadonlyArray<T>` ❌
There are also options to prefer [`"generic"`](https://typescript-eslint.io/rules/array-type/#generic) or [`"array-simple"`](https://typescript-eslint.io/rules/array-type/#array-simple)
Another option is to disable this rule entirely in `@hono/eslint-config`
> lint: array-type

- .changeset/rude-squids-shout.md
- packages/otel/src/index.test.ts
- packages/otel/src/index.ts
This implements the [Otel spec for expections](https://opentelemetry.io/docs/specs/otel/trace/exceptions/), recording them as events on the span. The main goal is to be able to see the stacktrace of a span with an error. The status of the spec seems to be `Development`, so I'm not sure what's the stance for this middleware, but for instance this is how the express Otel integration handles exceptions as well.
I've set the change to be a patch one but I'm not sure about that.
> feat(otel): record uncaught expections

- .changeset/easy-wombats-help.md
- packages/bun-transpiler/src/index.ts
- packages/bun-transpiler/tsconfig.build.json
As part of #740, I'm enabling [`isolatedDeclarations`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-5.html#isolated-declarations) to solve [JSR "slow types"](https://jsr.io/docs/about-slow-types)
> refactor(bun-transpiler): enable isolated declarations

- packages/ajv-validator/tsconfig.build.json
- packages/arktype-validator/tsconfig.build.json
- packages/bun-compress/tsconfig.build.json
- packages/casbin/tsconfig.build.json
- packages/class-validator/tsconfig.build.json
- packages/conform-validator/tsconfig.build.json
- packages/effect-validator/tsconfig.build.json
- packages/event-emitter/tsconfig.build.json
- packages/qwik-city/tsconfig.build.json
- packages/react-compat/tsconfig.build.json
- packages/react-renderer/tsconfig.build.json
- packages/standard-validator/tsconfig.build.json
- packages/standard-validator/tsconfig.spec.json
- packages/trpc-server/tsconfig.build.json
- packages/tsyringe/tsconfig.build.json
- packages/typebox-validator/tsconfig.build.json
- packages/typia-validator/tsconfig.build.json
- packages/valibot-validator/tsconfig.build.json
- packages/zod-validator/tsconfig.build.json
- tsconfig.json
This PR just enables `isolatedDeclarations` for all the workspaces that don't need changes, or a release
> refactor: enable isolated declarations

- .changeset/stale-insects-own.md
- packages/node-ws/src/index.test.ts
- packages/node-ws/src/index.ts
This change introduces the return of the WebSocketServer instance from the createNodeWebSocket function, enhancing its usability by allowing consumers access to the WebSocketServer instance for additional operations.
e.g. now users can do the following:
```
import { createNodeWebSocket } from '@hono/node-ws'
import { Hono } from 'hono'
import { serve } from '@hono/node-server'
const app = new Hono()
const { injectWebSocket, upgradeWebSocket, wss } = createNodeWebSocket({ app })
app.get(
'/ws',
upgradeWebSocket((c) => ({
// https://hono.dev/helpers/websocket
}))
)
const server = serve(app)
injectWebSocket(server)
wss.on('connection', (ws) => {
console.log('A new client connected!');
// Implement pingpong or something.
});
```
- Updated tests to verify the returned WebSocketServer instance …
> feat(node-ws): Add WebSocketServer instance return to createNodeWebSocket

- .github/workflows/cr.yml
Publish all packages from `main`
This feels a bit wasteful as it will end up publishing a lot of packages where nothing has changed. But I guess that is the point of `pkg.pr.new`, to make it easy to install any commit as a package
> chore(cr): publish all from main

- packages/graphql-server/package.json
Updates the package repository to fix the [build](https://github.com/honojs/middleware/actions/runs/15804770070/job/44547992257)
> chore(graphql-server): package repository

- .changeset/angry-points-throw.md
- packages/stytch-auth/README.md
- packages/stytch-auth/src/index.test.ts
- packages/stytch-auth/src/index.ts
Small change to pass a `STYTCH_DOMAIN` environment variable into the Stytch client constructors. This variable is used to direct the client to use a different baseURL for communication with the backend API, which is a useful thing for certain platform features such as OIDC Compliant issuers e.g. `https://login.example.com`.
> feat(stytch-auth): Add support for custom domain usage

- .changeset/petite-masks-melt.md
- packages/zod-openapi/package.json
- packages/zod-openapi/src/index.ts
- packages/zod-openapi/tsconfig.build.json
- yarn.lock
This is the last package to enable `isolatedDeclarations`
There is one issue where two methods use `ReturnType<typeof generator.generateDocument>`, which is too dynamic for JSR
https://github.com/honojs/middleware/blob/a7ee664c98b3a3089ac2f8c0df8c2b6f5470c64a/packages/zod-openapi/src/index.ts#L558-L574
Two solutions I can think of
1. Add `openapi3-ts` as a dependency and import the types directly
2. Update `@asteasolutions/zod-to-openapi` so it re-exports the necessary types from `openapi3-ts`
> refactor(zod-openai): enable isolated declarations

- .github/workflows/release.yml
This should prevent the release workflow from modifying `.yarnrc.yml`
From https://yarnpkg.com/configuration/yarnrc
> Finally, note that most settings can also be defined through environment variables (at least for the simpler ones; arrays and objects aren't supported yet). To do this, just prefix the names and write them in snake case: `YARN_CACHE_FOLDER` will set the cache folder (such values will overwrite any that might have been defined in the RC files - use them sparingly).
> refactor(release): use `YARN_NPM_AUTH_TOKEN`

- .github/workflows/release.yml
The latest Deno (2.4.0) seems to have an issue with module resolution. Let's try to use 2.3.7 for releasing for now.
related:
- https://github.com/jsr-io/jsr-npm/issues/129
- https://github.com/jsr-io/jsr-npm/pull/130
> chore: pin Deno to 2.3.7 in release workflow

- .changeset/six-candles-repeat.md
- packages/session/deno.json
- packages/session/src/index.ts
Changes the types for the `deleteCookie`, `getCookie`, and `setCookie` methods to match their usage
> fix(session): types for SessionOptions cookie methods

- .changeset/good-otters-press.md
- packages/auth-js/src/index.test.ts
- packages/auth-js/src/index.ts
This allows the config file to be generated async. 
Rationale / need: See (for example) the [split config](https://authjs.dev/guides/edge-compatibility#split-config) described in auth-js docs, where a database is used but not in all environments or not for all paths. Allowing an async config enables you to import the config that does / doesn't use the database based on whatever conditions you desire.
It also allows you to use things like cloudflare's [secret store](https://developers.cloudflare.com/secrets-store/integrations/workers/#call-get-on-the-binding-variable)(the api for which is exclusively async) for configuration variables.
> feat(auth-js): Support async ConfigHandler

- .changeset/shiny-views-grin.md
- packages/otel/src/index.test.ts
- packages/otel/src/index.ts
- Add `captureRequestHeaders` and `captureResponseHeaders` options to control which HTTP
headers are collected in OpenTelemetry spans
- Prevent sensitive information (cookies, authorization tokens) from being logged by default
- The 'Traceparent' and 'Tracestate' headers are always captured from requests
- Added `captureRequestHeaders?: string[]` option to specify which request headers to capture
- Added `captureResponseHeaders?: string[]` option to specify which response headers to capture
- Modified header collection logic to only capture explicitly specified headers
- Added comprehensive test coverage for the new functionality
**⚠️ Breaking Change**: By default, no headers are captured anymore. Previously, all headers
were captured automatically.
To maintain the previous behavior, …
> feat(otel): Support selective HTTP header capture

- .changeset/nasty-pears-sit.md
- packages/eslint-config/index.js
I think these formatting things should be done with a formatter like prettier, not ESLint. This resolves the conflict between prettier and eslint.
> fix(eslint-config): diable `quotes` and `semi` rules

- .changeset/warm-emus-clap.md
- packages/zod-openapi/README.md
- packages/zod-openapi/package.json
- packages/zod-openapi/src/index.test.ts
- packages/zod-openapi/src/index.ts
- yarn.lock
fixes #1349
This PR adds support for passing generator options to the `doc` function in `@hono/zod-openapi`, allowing users to customize OpenAPI v3.1 document generation.
```ts
// Before
app.doc31('/docs', { openapi: '3.1.0', info: { title: 'My API' } })
// After (optional generator options with backward compatibility)
app.doc31('/docs', 
{ openapi: '3.1.0', info: { title: 'My API' } },
{ unionPreferredType: 'oneOf' }
)
```
> feat(zod-openapi): Add optional generator options parameter to doc middleware

- .github/dependabot.yml
Looks like there was an issue with the initial configuration 😩 
https://github.com/honojs/middleware/runs/47402472825
```
Update configs must have a unique combination of 'package-ecosystem', 'directory', and 'target-branch'. Ecosystem 'npm' has overlapping directories.
```
It should now only update `devDependencies`
> chore: remove overlapping dependabot config

- .changeset/gentle-bugs-peel.md
- packages/oauth-providers/src/providers/github/authFlow.ts
hi, after github oauth, the framework attempted to obtain the email, but the contentType was missing. This request would report a 400 error. This PR supplemented this contentType
> fix(oauth-providers): github oauth

- .changeset/evil-rabbits-obey.md
- packages/otel/package.json
- packages/otel/src/index.test.ts
- packages/otel/src/index.ts
- yarn.lock
In some applications, when relatively small spans are produced, `startTime` & `endTime` may be required to have a higher precision than the default millisecond
This PR intends to support this by introducing a `getTime` option. When defined, this function is used for assigning `startTime` & `endTime` values to the spans
> feat(otel): support custom time input for span startTime & endTime

- .changeset/brave-bags-talk.md
- packages/oauth-providers/src/index.test.ts
- packages/oauth-providers/src/providers/msentra/msentraAuth.ts
Fixed a bug where the state parameter was not being passed to the MSEntra AuthFlow constructor, which could cause CSRF protection to fail. The state parameter is now properly passed from the middleware options to the AuthFlow instance.
> fix(oauth-providers): pass missing state param to MSEntra AuthFlow

- .changeset/wise-masks-say.md
- packages/zod-validator/src/index.ts
- packages/zod-validator/src/v3.test.ts
- packages/zod-validator/src/v4.test.ts
Fixes #1370
This PR enables preventing enum types from falling back to `string | string[]` when `coerce` is used.
> fix(zod-validator): correct fallback behavior when using `coerce`

- package.json
- yarn.lock
Add `typia` to root workspace
It looks like `@ryoppippi/unplugin-typia` and `typia` are imported when `vitest` is resolving `project` configuration
https://github.com/honojs/middleware/blob/06073bcf0379e5c56be4378a68542664515e2a25/packages/typia-validator/vitest.config.ts#L1
There is no issue when both dependencies are installed, for example, when the CI workflow for `@hono/typia-validator` is run.
But it is an issue for other workspaces when the packages aren't installed 😭 `@ryoppippi/unplugin-typia` was already included in the root workspace, we just need to include `typia` too.
> ci: add typia to root workspace
