honojs/middleware

.changeset/late-shoes-drive.md
.github/workflows/ci-typebox-validator.yml
package.json
packages/typebox-validator/CHANGELOG.md
packages/typebox-validator/README.md
packages/typebox-validator/jest.config.js
packages/typebox-validator/package.json
packages/typebox-validator/src/index.ts
packages/typebox-validator/test/index.test.ts
packages/typebox-validator/tsconfig.cjs.json
packages/typebox-validator/tsconfig.esm.json
packages/typebox-validator/tsconfig.json
packages/zod-validator/README.md
yarn.lock

Hi Yusuke,
Thanks for making Hono. It's a simple and excellent framework.
I'd like to add [TypeBox](https://github.com/sinclairzx81/typebox) as a validator middleware. I based the implementation off of the zod validator and took the test cases from there also. Please let me know if you have any questions or concerns.

feat(typebox-validator): Add TypeBox Validator middleware

---

.changeset/breezy-clocks-end.md
.github/workflows/ci-medley-router.yml
package.json
packages/medley-router/README.md
packages/medley-router/jest.config.js
packages/medley-router/package.json
packages/medley-router/src/index.test.ts
packages/medley-router/src/index.ts
packages/medley-router/src/router.ts
packages/medley-router/tsconfig.json
yarn.lock

feat: add "medley-router"

---

.changeset/strong-hotels-kiss.md
packages/sentry/deno_dist/index.ts
packages/sentry/src/index.ts
packages/sentry/src/replacer.ts
packages/sentry/test/index.test.ts

fix(sentry): fixed sentry options types

---

.changeset/rich-birds-raise.md
packages/zod-openapi/src/index.ts
packages/zod-openapi/test/index.test.ts

fix(zod-openapi): fix path param format `:id` to `{id}`

---

.changeset/hungry-frogs-collect.md
packages/sentry/README.md
packages/sentry/deno_dist/index.ts
packages/sentry/deno_test/deps.ts
packages/sentry/package.json
packages/sentry/src/index.ts
packages/sentry/src/replacer.ts
packages/sentry/test/index.test.ts
yarn.lock

feat(sentry): bump up `toucan-js` to v3

---

.changeset/slow-planets-care.md
packages/zod-openapi/package.json
packages/zod-openapi/src/index.ts
yarn.lock

fix(zod-openapi): fix the type error

---

.changeset/sweet-insects-attack.md
packages/zod-openapi/README.md
packages/zod-openapi/src/index.ts

feat(zod-openapi): make `app.openAPIRegistry` public

---

.changeset/mighty-clouds-double.md
.github/workflows/ci-typia-validator.yml
package.json
packages/typia-validator/README.md
packages/typia-validator/jest.config.js
packages/typia-validator/package.json
packages/typia-validator/src/index.ts
packages/typia-validator/test/index.test.ts
packages/typia-validator/tsconfig.cjs.json
packages/typia-validator/tsconfig.esm.json
packages/typia-validator/tsconfig.json
yarn.lock

This is a validator using [Typia](https://github.com/samchon/typia). The code is based on `zod-validator`.

Add Typia validator

---

.changeset/shiny-actors-scream.md
packages/zod-openapi/package.json
packages/zod-openapi/src/index.ts
packages/zod-openapi/test/index.test.ts
yarn.lock

fix(zod-openapi): multiple routes types correct for `hc`

---

.changeset/make-http-exception-2.md
packages/firebase-auth/src/index.ts

fix 2 for https://github.com/honojs/middleware/issues/185

fix(firebase-auth): throw HTTPException for bad request

---

.changeset/wild-glasses-own.md
.github/workflows/ci-clerk-auth.yml
package.json
packages/clerk-auth/README.md
packages/clerk-auth/jest.config.js
packages/clerk-auth/package.json
packages/clerk-auth/src/index.ts
packages/clerk-auth/test/index.test.ts
packages/clerk-auth/tsconfig.json
yarn.lock

This PR adds a middleware that will help easily integrate user authentication and user management by [Clerk](https://clerk.com) to your Hono application.

Clerk Middleware

---

.changeset/six-shirts-dress.md
packages/zod-openapi/package.json
packages/zod-openapi/src/index.ts
yarn.lock

fix(zod-openapi): import types correctly

---

packages/clerk-auth/README.md

This PR fixes a typo in the README.md of the Clerk Middleware.

chore(clerk-auth): Update README.md

---

.changeset/wicked-mayflies-pay.md
.github/workflows/ci-esbuild-transpiler.yml
packages/esbuild-transpiler/README.md
packages/esbuild-transpiler/package.json
packages/esbuild-transpiler/src/index.ts
packages/esbuild-transpiler/src/transpiler.ts
packages/esbuild-transpiler/src/transpilers/node.ts
packages/esbuild-transpiler/src/transpilers/wasm.ts
packages/esbuild-transpiler/src/types.esbuild.ts
packages/esbuild-transpiler/test/node.test.ts
packages/esbuild-transpiler/tsconfig.json
yarn.lock

This PR introduces "esbuild Transpiler Middleware".
The original idea is proposed by #224. But this Middleware is using the esbuild and support using a Wasm for edge platforms.

feat: esbuild Transpiler Middleware

---

packages/swagger-ui/README.md

Hi, @yusukebe 
I found some mistakes of the document.

docs: not to escape with SwaggerUI html

---

.changeset/fix-default-key-store-initializer.md
packages/firebase-auth/README.md
packages/firebase-auth/package.json
packages/firebase-auth/src/index.ts
packages/firebase-auth/test/index.test.ts
packages/firebase-auth/tsconfig.json
yarn.lock

This fix comes as a set with this: https://github.com/Code-Hex/firebase-auth-cloudflare-workers/pull/10

fixed firebase-auth for #247

---

.changeset/soft-llamas-melt.md
packages/swagger-ui/src/swagger/renderer.ts
packages/swagger-ui/test/option-renderer.test.ts

fix(swagger-ui): support `persistAuthorization` and boolean option

---

.changeset/chilled-kids-complain.md
.changeset/pretty-brooms-sparkle.md
package.json

fix(oauth-providers): enable building

---

.changeset/chilled-donkeys-report.md
.changeset/pretty-brooms-sparkle.md
packages/zod-openapi/package.json
packages/zod-openapi/src/index.ts
packages/zod-openapi/test/index.test.ts
yarn.lock

Fixes https://github.com/honojs/hono/issues/1775

fix(zod-openapi): Strict type checking of return values

---

packages/zod-openapi/README.md

docs: add "how to register schema with refs"

---

.changeset/seven-eagles-explain.md
packages/oauth-providers/README.md
packages/oauth-providers/package.json
packages/oauth-providers/src/providers/github/authFlow.ts
packages/oauth-providers/src/providers/x/authFlow.ts
packages/oauth-providers/src/providers/x/index.ts
packages/oauth-providers/src/providers/x/refreshToken.ts
packages/oauth-providers/src/providers/x/revokeToken.ts
packages/oauth-providers/src/providers/x/types.ts
packages/oauth-providers/src/providers/x/xAuth.ts
packages/oauth-providers/src/utils/getCodeChallenge.ts
packages/oauth-providers/test/handlers.ts
packages/oauth-providers/test/index.test.ts

Provides data:
- token
- reresh_token
- granted_scopes
- user-x
Provides methods:
- refreshToken
- revokeToken

Add X (Twitter) to OAuth providers

---

.changeset/chatty-phones-rest.md
packages/zod-openapi/src/index.ts
packages/zod-openapi/test/index.test.ts

fix(zod-openapi): supports named params in nested routes

---

.changeset/fuzzy-grapes-play.md
packages/qwik-city/README.md

🙌 
The Qwik City's actions request against the method POST.
In the event Qwik City may request against the others, I changed to use the `all` instead of the `get`.
(1) Open to comments; (2) shall I create a branch?

docs(qwik-city) support all request methods

---

packages/zod-openapi/README.md

docs update for deprecated expression

docs: replace jsonT with json

---

.changeset/beige-sloths-raise.md
packages/auth-js/package.json
yarn.lock

@yusukebe  react should be added as peer  dependency some how I missed in 1st pr.

added react as peer

---

.changeset/nice-crews-glow.md
packages/oauth-providers/README.md
packages/oauth-providers/package.json
packages/oauth-providers/src/providers/discord/authFlow.ts
packages/oauth-providers/src/providers/discord/discordAuth.ts
packages/oauth-providers/src/providers/discord/index.ts
packages/oauth-providers/src/providers/discord/refreshToken.ts
packages/oauth-providers/src/providers/discord/revokeToken.ts
packages/oauth-providers/src/providers/discord/types.ts
packages/oauth-providers/test/handlers.ts
packages/oauth-providers/test/index.test.ts

**_Provides data_**:
- token
- refresh_token
- granted_scopes
- user-discord
**_Provides methods_**:
- refreshToken
- revokeToken

Add Discord to OAuth Providers

---

.changeset/seven-fireants-teach.md
.github/workflows/ci-bun-transpiler.yml
package.json
packages/bun-transpiler/README.md
packages/bun-transpiler/package.json
packages/bun-transpiler/src/index.test.ts
packages/bun-transpiler/src/index.ts
packages/bun-transpiler/tsconfig.json
packages/bun-transpiler/vitest.config.ts
yarn.lock

Add Bun Transpiler middleware #344

---

packages/zod-openapi/README.md

I had to change it like this to get it working
Here are my versions:
"@hono/swagger-ui": "0.2.1",
"@hono/zod-openapi": "0.9.5",
"hono": "3.12.6"

update readme to show new security schema usage

---

.changeset/cold-singers-bow.md
packages/auth-js/package.json
packages/auth-js/src/index.ts
yarn.lock

@yusukebe  this  PR add supports for new authjs core   versions.Auth js core package   has  done major changes  which broke  previous code.

Update @auth/core version and set default basePath

---

.changeset/sharp-fans-explain.md
.changeset/sixty-ladybugs-travel.md
packages/oauth-providers/src/providers/github/authFlow.ts
packages/oauth-providers/src/providers/github/types.ts
packages/oauth-providers/test/handlers.ts

When trying authentication with Github App, Github only sends the user's profile public email if there is any we receive `null`.
I am now explicitly requesting user emails to get a non-null value.

OAuth Providers Github App email problem

---

.changeset/kind-donuts-boil.md
packages/zod-openapi/src/index.ts
packages/zod-openapi/test/index.test-d.ts
packages/zod-openapi/test/index.test.ts

fix(zod-openapi): BasePath not included in client types

---

.changeset/yellow-ways-refuse.md
packages/esbuild-transpiler/src/transpiler.ts
packages/esbuild-transpiler/test/node.test.ts

fix(esbuild-transpiler): set a content-type correctly

---

.changeset/chilly-pumas-hear.md
packages/react-renderer/package.json
packages/react-renderer/src/react-renderer.ts
packages/react-renderer/test/react-renderer.test.tsx
yarn.lock

Although nested layout is supported in jsx-renderer, it did not seem to be supported in react-renderer yet. By merging this PR, nested layout will be available in react-renderer.

feat(react-renderer): Nested layout support for react-renderer

---

packages/react-renderer/README.md

According #467, We update the `react-renderer` to show how to support SSR with React.

add react ssr document

---

.changeset/warm-jobs-fold.md
packages/prometheus/package.json
yarn.lock

fix(prometheus): bump peer dependency

---

.changeset/dull-carrots-wash.md
packages/trpc-server/README.md
packages/trpc-server/src/index.ts
packages/trpc-server/test/context.test.ts

this would solve #455
change should be backwards compatible (so not bumping the minor version).

feat(trpc): access hono context from trpc procedures

---

.changeset/dull-ravens-smash.md
packages/auth-js/src/index.ts

It is the same URL base issue as #478, sorry for not fully fixing it last time.

fix(auth-js): AUTH_URL not working in getAuthUser

---

packages/clerk-auth/src/index.ts
packages/clerk-auth/test/index.test.ts
packages/oidc-auth/src/index.ts
packages/oidc-auth/test/index.test.ts
packages/trpc-server/src/index.ts
packages/trpc-server/test/context.test.ts
packages/zod-openapi/src/index.ts
packages/zod-openapi/test/index.test.ts

refactor: format

---

.changeset/soft-roses-kick.md
packages/sentry/package.json
yarn.lock

feat(sentry): support esm

---

.changeset/red-colts-retire.md
packages/zod-openapi/src/index.ts

fixes https://github.com/honojs/middleware/issues/509

fix(zod-openapi): add Promise<void> to Hook

---

.changeset/quick-icons-add.md
packages/valibot-validator/src/index.ts
packages/valibot-validator/test/index.test.ts

[valibot-validator] Add supports async validation

---

.changeset/curly-pears-act.md
packages/zod-openapi/src/index.ts
packages/zod-openapi/test/index.test-d.ts

Fixes https://github.com/honojs/hono/issues/2968

fix(zod-openapi): use `JSONParsed` for creating a response type

---

.changeset/honest-shrimps-change.md
packages/zod-openapi/src/index.ts
packages/zod-openapi/test/index.test.ts

fix(zod-openapi): remove the type error for the hook

---

.changeset/chatty-dragons-juggle.md
packages/auth-js/src/index.ts

@yusukebe this pr fixes  https://github.com/honojs/middleware/issues/613 which was introduced in 1.0.9

Fix immutable headers error in x-forwarded request

---

.changeset/thirty-waves-play.md
packages/zod-openapi/src/index.ts
packages/zod-openapi/test/index.test-d.ts

Fixes https://github.com/honojs/hono/issues/3106

fix(zod-openapi): support `coerce`

---

.changeset/warm-flies-count.md
packages/swagger-ui/package.json
packages/swagger-ui/src/swagger/renderer.ts
packages/swagger-ui/test/option-renderer.test.ts
yarn.lock

This PR introduces new rendering options for Swagger UI, enhancing configurability and updating dependencies for improved compatibility.
1. **Dependency Update:**
- Update `@types/swagger-ui-dist` to `^3.30.5`.
2. **New Rendering Options:**
- Add options such as `queryConfigEnabled`, `displayOperationId`, `tagsSorter`, `useUnsafeMarkdown`, `onComplete`, `syntaxHighlight`, `tryItOutEnabled`, `requestSnippets`, `oauth2RedirectUrl`, `showMutableRequest`, `request`, `supportedSubmitMethods`, `validatorUrl`, `withCredentials`, `modelPropertyMacro`, `parameterMacro`.
3. **Renderer and Test Updates:**
- Apply rendering types and add test cases for each new option.
- Fix type errors in test cases and refactor tests using `it.each` for better readability and maintenance.
ref: …

feat(swagger-uri): Add Full Configuration Parameters and Update Dependencies

---

.changeset/smart-cherries-kick.md
packages/react-renderer/src/index.ts

fix(react-renderer): Change react-renderer props to interface

---

.changeset/twelve-singers-watch.md
packages/zod-openapi/src/index.ts
packages/zod-openapi/test/index.test.ts

Fixes https://github.com/honojs/middleware/issues/685#issuecomment-2282284170

fix(zod-openapi): supports `required` for JSON and Form body

---

.changeset/curly-eagles-relate.md
packages/zod-openapi/src/index.ts
packages/zod-openapi/test/handler.test-d.ts

fix(zod-openapi): support default response

---

.changeset/giant-eyes-perform.md
packages/typebox-validator/src/index.ts
packages/typebox-validator/test/index.test.ts

Added ability to remove properties that are not in the schema to emulate other validators like zod

feat(typebox-validator): Add strict schema

---

.changeset/cool-coats-try.md
packages/node-ws/src/index.ts

fix(node-ws): websocket upgrade header value case sensitivity

---

packages/zod-openapi/README.md

Add docs if the proper Content-Type is lacking in a request. And added about `request.body.required`.
Related to #891

docs(zod-openapi): add docs for lacking proper Content-Type in a request

---

.changeset/witty-mayflies-hunt.md
packages/firebase-auth/package.json
yarn.lock

Updated versions for a few of dependencies for https://github.com/honojs/middleware/issues/912

update(firebase-auth): updated firebase deps

---

.changeset/small-turtles-relax.md
packages/standard-validator/src/index.ts

There was slight overlook, and one dead function was left

fix(standard-validator): remove dead code

---

.changeset/rude-pumpkins-compete.md
packages/zod-validator/package.cjs.json
packages/zod-validator/package.json

fix(zod-validator): fix commonjs import problem

---

.changeset/sixty-geese-knock.md
packages/cloudflare-access/src/index.test.ts
packages/cloudflare-access/src/index.ts

feat(cloudflare-access): Add support to read JWT from Cookie

---

.github/workflows/ci-oauth-providers.yml
packages/oauth-providers/package.json
packages/oauth-providers/vitest.config.ts
yarn.lock

One step closer to Vitest v3 🎉 
Fixes #1003

test(oauth-providers): use node 20.x in CI

---

.github/workflows/ci-ajv-validator.yml
package.json
packages/ajv-validator/package.json
packages/ajv-validator/tsconfig.json
packages/ajv-validator/tsup.config.ts
tsup.config.ts
yarn.lock

I'm looking at aligning the `build`/`test`/`release` scripts in each workspace. This is the template that I'll aim to follow for each workspace. If we get this right, the rest will be pretty straightforward

build(ajv-validator): lint published package

---

packages/zod-openapi/src/index.ts

refactor(zod-openapi): fix type errors

---

packages/typebox-validator/src/index.ts

refactor(typebox-validator): fix the type error

---

.changeset/hot-results-dream.md
packages/sentry/src/index.test.ts
packages/sentry/src/index.ts

fix(sentry): fix the type error

---

packages/eslint-config/index.js

fix(eslint-config): add spread to `tseslint.configs.recommended`

---

.changeset/spotty-things-rule.md

chore(eslint-config): add missing changeset

---

.changeset/tasty-sides-ring.md
packages/react-renderer/src/react-renderer.ts

fix(react-renderer): tweak dynamic importing `renderToReadableStream`

---

.changeset/deep-rivers-attend.md
packages/node-ws/src/index.test.ts
packages/node-ws/src/index.ts

fix(node-ws):missing code and reason on CloseEvent

---

packages/ajv-validator/src/index.ts
packages/arktype-validator/src/index.ts
packages/auth-js/src/react.tsx
packages/class-validator/src/index.ts
packages/conform-validator/src/index.ts
packages/effect-validator/src/index.ts
packages/event-emitter/src/index.ts
packages/oauth-providers/src/providers/twitch/types.ts
packages/prometheus/src/standardMetrics.ts
packages/standard-validator/src/index.test.ts
packages/standard-validator/src/index.ts
packages/swagger-ui/src/swagger/renderer.ts
packages/typebox-validator/src/index.ts
packages/typia-validator/src/http.ts
packages/typia-validator/src/index.ts
packages/valibot-validator/src/index.ts
packages/zod-openapi/src/index.ts
packages/zod-validator/src/index.ts

chore: format codes

---

.changeset/tame-rooms-hide.md
packages/zod-validator/README.md
packages/zod-validator/src/index.test.ts
packages/zod-validator/src/index.ts

This PR introduces a new option called `validationFunction`.
This will resolve the issue addressed in #1130

feat(zod-validator): add `validationFunction` option

---

.github/workflows/codestyle.yml

The current actions doesn't check if pull requests are formatted with prettier. This can make new pull requests which were formatted have diffs that's nothing to do with the PR.
In this PR, added action `codestyle` checks if pull requests have formatted.

ci: add codestyle ci

---

.github/workflows/ci-bun-compress.yml
packages/bun-compress/vitest.config.ts

- Fixes the import for `vitest/config`
- Add a CI workflow

test(bun-compress): fix vitest config

---

.changeset/sixty-cobras-live.md
packages/oauth-providers/README.md
packages/oauth-providers/mocks.ts
packages/oauth-providers/package.json
packages/oauth-providers/src/index.test.ts
packages/oauth-providers/src/providers/msentra/authFlow.ts
packages/oauth-providers/src/providers/msentra/index.ts
packages/oauth-providers/src/providers/msentra/msentraAuth.ts
packages/oauth-providers/src/providers/msentra/refreshToken.ts
packages/oauth-providers/src/providers/msentra/types.ts

I've recreated #1017 to remove all the extra git commits. Sorry for all the noise @TimBarley
Fixes #1017

feat(oauth-providers): Add MSEntra OAuth Provider

---

packages/oauth-providers/package.json

Fixes the publish issue noticed in https://github.com/honojs/middleware/pull/1163#issuecomment-2885249764
> Payment Required??
> 
> [honojs/middleware/actions/runs/15056602674/job/42324518355#step:7:274](https://github.com/honojs/middleware/actions/runs/15056602674/job/42324518355#step:7:274)

ci(oauth-providers): set publish config access to public

---

.changeset/great-toys-knock.md
packages/auth-js/src/index.test.ts
packages/auth-js/src/index.ts

fix(auth-js): use HonoRequest.blob() instead of HonoRequest.raw.body()

---

.changeset/shaggy-lies-go.md
packages/node-ws/src/index.test.ts
packages/node-ws/src/index.ts

Closes #1129, using buffering.

fix(node-ws): use buffering to fix #1129

---

.changeset/large-areas-take.md
packages/clerk-auth/src/index.ts
packages/clerk-auth/tsconfig.build.json

refactor(clerk-auth): enable isolated declarations

---

.changeset/tangy-forks-travel.md
packages/esbuild-transpiler/src/transpiler.ts
packages/esbuild-transpiler/src/transpilers/node.ts
packages/esbuild-transpiler/src/transpilers/wasm.ts
packages/esbuild-transpiler/tsconfig.build.json

refactor(esbuild-transpiler): enable isolated declarations

---

.changeset/huge-clocks-behave.md
packages/graphql-server/src/index.ts
packages/graphql-server/tsconfig.build.json

Add explicit `Response` return type

refactor(graphql-server): enable isolated declarations

---

.changeset/bumpy-birds-act.md
packages/hello/src/index.ts
packages/hello/tsconfig.build.json

refactor(hello): enable isolated declarations

---

.changeset/grumpy-bags-stop.md
packages/medley-router/src/router.ts
packages/medley-router/tsconfig.build.json

Add explicit `void` return type

refactor(medley-router): enable isolated declarations

---

.changeset/rich-actors-flow.md
packages/sentry/src/index.ts
packages/sentry/tsconfig.build.json

Add explicit `Toucan` return type

refactor(sentry): enable isolated declarations

---

.changeset/giant-pets-double.md
packages/oauth-providers/src/providers/discord/authFlow.ts
packages/oauth-providers/src/providers/facebook/authFlow.ts
packages/oauth-providers/src/providers/github/authFlow.ts
packages/oauth-providers/src/providers/google/authFlow.ts
packages/oauth-providers/src/providers/google/revokeToken.ts
packages/oauth-providers/src/providers/linkedin/authFlow.ts
packages/oauth-providers/src/providers/msentra/authFlow.ts
packages/oauth-providers/src/providers/msentra/refreshToken.ts
packages/oauth-providers/src/providers/twitch/authFlow.ts
packages/oauth-providers/src/providers/x/authFlow.ts
packages/oauth-providers/tsconfig.build.json

refactor(oauth-providers): enable isolated declarations

---

.changeset/busy-clouds-walk.md
packages/prometheus/src/index.ts
packages/prometheus/src/standardMetrics.ts
packages/prometheus/tsconfig.build.json

refactor(prometheus): enable isolated declarations

---

.changeset/lemon-rats-pull.md
packages/swagger-editor/src/index.ts
packages/swagger-editor/tsconfig.build.json

refactor(swagger-editor): enable isolated declarations

---

.changeset/grumpy-turkeys-flow.md
packages/swagger-ui/src/index.ts
packages/swagger-ui/src/swagger/renderer.ts
packages/swagger-ui/tsconfig.build.json

refactor(swagger-ui): enable isolated declarations

---

.changeset/wise-trams-like.md
packages/otel/src/index.ts
packages/otel/tsconfig.build.json

refactor(otel): enable isolated declarations

---

yarn.lock

chore: update the lockfile

---

.changeset/six-hoops-find.md

chore(graphql-server): publish package repository

---

.changeset/eager-lemons-sit.md

chore(react-compat): publish package

---

.changeset/dark-crabs-go.md
packages/clerk-auth/package.json
yarn.lock

This pull request is related to : https://github.com/honojs/middleware/issues/1261

chore(clerk): 🆙 updated clerk dependency ( https://github.com/honojs/middleware/issues/1261 )

---

.github/workflows/ci.yml

ci: specify the deno version `2.3.7` for dry-run

---

.changeset/mean-rice-spend.md
packages/zod-validator/src/index.ts
packages/zod-validator/src/v4.test.ts

fix(zod-validator): support transform

---

packages/zod-openapi/src/index.ts

fix(zod-openapi): correct importing `zod`

---

.changeset/rare-monkeys-play.md

chore: add changeset

---

packages/mcp/deno.json

chore(mcp): fix the version mismatch for `deno.json`

---

packages/bun-compress/tsconfig.spec.json

chore(bun-compress): correct output directory

---

packages/tsyringe/README.md

docs(tsyringe): fix incorrect usage example

---

.github/workflows/autofix.yml

Copying the workflow added in honojs/hono#4322

chore: autofix ci

---

.changeset/bright-parents-fry.md
packages/oauth-providers/mocks.ts
packages/oauth-providers/src/index.test.ts
packages/oauth-providers/src/providers/google/authFlow.ts
packages/oauth-providers/src/providers/google/googleAuth.ts
packages/oauth-providers/src/providers/google/types.ts

ref: https://github.com/honojs/middleware/issues/1340

fix(oauth-providers): Fix/1340

---

.changeset/rude-stars-agree.md
packages/mcp/deno.json

chore(mcp): fix the version mismatch beween jsr and npm

---

.changeset/tiny-seals-beam.md
packages/mcp/deno.json

chore(mcp): bump the version for jsr
